### ISSUE TITLE
Operator's memory usage over time

### ISSUE THREAD

**Issue by ssro** [appscode/voyager#1004]
Hi everyone,

I've noticed that the operator, over time, starts to use more and more memory without releasing it back to the OS. Is this normal? Screenshot below is for almost 2 weeks. I've had much more memory usage before (about 3G), when the operator was running for more than 2 months without restart.

Verision of the operator is 5.0.0-rc.11, kubernetes version v1.8.8. Cluster was deployed with kops.

<img width="1417" alt="screen shot 2018-04-30 at 09 06 54" src="https://user-images.githubusercontent.com/13402690/39413604-d722950c-4c56-11e8-823b-21afc941a7b1.png">

Thank you

**Comment by tamalsaha** [comment]
@ssro , this is not normal. If you can share pprof profile that can hint at potential source of memory leaks. FYI, there has been significant updates to codebase since 5.0.0-rc.11 release. Any chance you can try the latest version and see this problem repeats itself?

**Comment by ssro** [comment]
Hi @tamalsaha, not sure what you mean by `pprof profile`. How do I get it? As of today, I've deployed version 6.0.0 (`appscode/voyager:6.0.0`) on a dev cluster. I can monitor this and report back in few days.

Thank you

**Comment by tamalsaha** [comment]
Thanks @ssro . By pprof I was referring to https://blog.golang.org/profiling-go-programs
https://golang.org/pkg/runtime/pprof/..

If ok, let's see how things turn out after 24 hours.

**Comment by ssro** [comment]
Hi @tamalsaha, 24hrs later problem persists

<img width="682" alt="screen shot 2018-05-01 at 23 57 11" src="https://user-images.githubusercontent.com/13402690/39483085-7780b052-4d9b-11e8-96e1-a574e92fcc6e.png">

Since i'm not "skilled" in memory profiling, any guidance towards carrying out this task would be appreciated

**Comment by antihax** [comment]
I am also running into the same issue. 
Is http/pprof compiled in or will I need to make a custom image?
Will try to trace it down tonight.

**Comment by tamalsaha** [comment]
>  Is http/pprof compiled in or will I need to make a custom image?
Yes. https://github.com/appscode/voyager/blob/master/pkg/cmds/run.go#L5

**Comment by antihax** [comment]
It appears to be leaking goroutines, there are ~40k of these:
```
goroutine 614034 [chan receive, 13854 minutes]:
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x3ec1a60, 0xc42255aae0, 0xc422982fc0)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/record/event.go:229 +0xac
created by github.com/appscode/voyager/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/record/event.go:226 +0x6e

goroutine 615600 [chan receive, 13844 minutes]:
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc4218dd000)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/watch/mux.go:208 +0x61
created by github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xfe
```

Trying to see if i can identify why these are hanging around.

**Comment by tamalsaha** [comment]
I wonder https://github.com/kubernetes/kubernetes/pull/61894/files pr has something related to this.

**Comment by tamalsaha** [comment]
I think I see what is going on. We create a new `EventRecorder` every time and never Stop() them. So, go routine never exits. https://github.com/appscode/voyager/blob/master/vendor/k8s.io/client-go/tools/record/event.go#L226

**Comment by tamalsaha** [comment]
I have pushed a new operator image with the fix. Can you update your voyager-operator image to `appscode/voyager:fix-leak` and check?

**Comment by antihax** [comment]
It's running now, i'll keep an eye on it and report back later. Thanks for looking into this so quickly.

**Comment by antihax** [comment]
still 53mb. looks like this resolved the leak.

**Comment by ssro** [comment]
That is fantastic @antihax ! Hope @tamalsaha will cut a release with this

**Comment by tamalsaha** [comment]
Thank you guys! This will be part of the next release 7.2.0 . I am targeting for next Monday.

**Comment by tamalsaha** [comment]
@antihax, @ssro reported that he is still seeing memory increase over time. Do you see any issues on your setup?

**Comment by ssro** [comment]
This is the graph for the last 2 days running `fix-leak` image. I think it's consuming memory somewhat slower since my first report about it.

<img width="1381" alt="screen shot 2018-06-21 at 13 40 04" src="https://user-images.githubusercontent.com/13402690/41715427-9e9c78e2-757d-11e8-8c87-4e60540974f1.png">

**Comment by antihax** [comment]
Unfortunately I restarted Prometheus last night. Here is what I see

https://i.imgur.com/YaNnOwR.png

**Comment by tamalsaha** [comment]
Folks, please keep an eye on it. It you see this, let me know with profiling data. I added a doc for that https://github.com/appscode/voyager/blob/master/docs/guides/ingress/monitoring/operator-profiling.md

**Comment by ssro** [comment]
Hi folks, a quick update of this issue. I have the same image (`fix-leak`) deployed to another cluster, same setup, and it looks stable for the last day. I see the same behavior to my original dev cluster. I will keep monitoring it over the weekend and report back, but so far, things are looking good.

Last day:

<img width="1051" alt="screen shot 2018-06-22 at 14 31 38" src="https://user-images.githubusercontent.com/13402690/41763666-07db03d6-7629-11e8-96ce-c5b804235bdc.png">

Last 3 days:

<img width="1048" alt="screen shot 2018-06-22 at 14 32 38" src="https://user-images.githubusercontent.com/13402690/41763712-28275432-7629-11e8-82c5-4ed5bb7bdf14.png">

**Comment by ssro** [comment]
Hi y'all,

Good news: the memory leak issue can be closed, the graph for the last 6 days shows that the memory consumption is stable.

<img width="1047" alt="screen shot 2018-06-25 at 08 56 17" src="https://user-images.githubusercontent.com/13402690/41826740-04676e18-7856-11e8-954d-91532d800b50.png">

**Comment by tamalsaha** [comment]
Thanks @ssro !
