### ISSUE TITLE
question re: ssl-passthrough

### ISSUE THREAD

**Issue by mikecargal** [appscode/voyager#1012]
At [https://github.com/appscode/voyager/blob/master/docs/guides/ingress/configuration/ssl-passthrough.md](https://github.com/appscode/voyager/blob/master/docs/guides/ingress/configuration/ssl-passthrough.md) the sample yaml references a "secret" (named "tls-secret" in the example).

Perhaps I'm misunderstanding what is meant by ssl-passthrough.  I would not expect the HAProxy to need a secret to pass the TLS content on.  

If it's not necessary, then what purpose is it solving?  We're struggling to understand what "secret" this would be.  Would it need to be a cert that was generated and then place in the /etc/ssl/private/haproxy/tls/ directory?

**Comment by tamalsaha** [comment]
SSL certificate should not be needed in this case. This was a bug . We are fixing it as part of https://github.com/appscode/voyager/pull/805

**Comment by tamalsaha** [comment]
Fixed in master
