### ISSUE TITLE
Letsencrypt wildcard certs?

### ISSUE THREAD

**Issue by delcon** [appscode/voyager#1024]
I was following the guide to issue http Letsencript certificates. https://appscode.com/products/voyager/6.0.0/guides/certificate/http/overview/
  
Is it possible to use wildcard certificates with voyager?  
And if it is, how would we configure voyager?

**Comment by tamalsaha** [comment]
Wildacrd certificate support has been added to master branch and will go out in next release . https://github.com/appscode/voyager/pull/996

We are hoping to get the next release out fairly soon. Going to merge pr #805 and cut release.

In the meantime, you can manually issue a wildcard certificate and put that in a Secret and provide to Voyager. https://github.com/tamalsaha/voyager-wildcard/blob/master/gavin/ing.yaml

**Comment by tamalsaha** [comment]
Fixed by https://github.com/appscode/voyager/releases/tag/7.0.0-rc.0
