### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by rimusz** [appscode/voyager#113]
used to be the helm chart to install `voyager`, but I see it is gone.
any plans to add it back?

**Comment by TamalSaha** [comment]
@rimusz , we have moved the chart to root directory. https://github.com/appscode/voyager/tree/master/chart/voyager

**Comment by rimusz** [comment]
my bad, did not notice there :)

**Comment by TamalSaha** [comment]
:). Please try the new 1.5.5 just released https://github.com/appscode/voyager/releases/tag/1.5.5 .
