### ISSUE TITLE
Support EKS

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#1130]
EKS does not support Kubernetes aggregation layer. So, Voyager can't be used there.

**Comment by jodem** [comment]
HI, I would love to test Voyager with EKS, any plan on supporting EKS ? thanks

**Comment by RisingPhorce** [comment]
We are considering EKS as well.  I would be interested in this feature.

**Comment by tamalsaha** [comment]
Folks, @arun-gupta tells me that EKS is looking into supporting aggregation layer. This is great news! There is no set date when this will be available. For now, we are just going to wait.

**Comment by tamalsaha** [comment]
This has been fixed in https://github.com/appscode/voyager/releases/tag/8.0.0

**Comment by alexkreidler** [comment]
According to [this AWS documentation page](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html) it seems like the newest versions of EKS now support both the aggregation layer and webhooks.

Any updates?
