### ISSUE TITLE
tls-backend annotation ignored for external service

### ISSUE THREAD

**Issue by enver** [appscode/voyager#1139]
I've tried to setup external service as ingress backend using example found [here](https://appscode.com/products/voyager/6.0.0/guides/ingress/http/external-svc/). Additionally I've added backend-tls annotation to so backend sends requests via SSL:

```apiVersion: v1
kind: Service
metadata:
  name: google
  namespace: local
  annotations:
    ingress.appscode.com/backend-tls: "ssl verify required"
    ingress.appscode.com/use-dns-resolver: "true"
    ingress.appscode.com/dns-resolver-nameservers: '["8.8.8.8:53", "8.8.4.4:53"]'
spec:
  externalName: google.com
  type: ExternalName
```

However backend-tls annotation is ignored as corresponding haproxy config look like
```
server external google.com:80   check   resolvers google.com resolve-prefer ipv4
```

It seems that [code parsing external service](https://github.com/appscode/voyager/blob/357522db9d6acc8769618f5af4730368755d4700/pkg/ingress/parser.go#L50-L70) ignores all but dns-resolver annotations. I can submit PR to include backend-tls annotations (an maybe others if you can point me to the right direction) like:

```
                        ep.DNSResolver = resolver.Name
                        ep.CheckHealth = resolver.CheckHealth
                }
+               if service.Annotations != nil {
+                       ep.TLSOption = service.Annotations[api.BackendTLSOptions]
+               }
                return &hpi.Backend{Endpoints: []*hpi.Endpoint{&ep}}, nil
        }
        p, ok := getSpecifiedPort(service.Spec.Ports, port)
```

**Comment by tamalsaha** [comment]
Thanks @enver ! Please send us a pr.
