### ISSUE TITLE
Crash when operator container starts

### ISSUE THREAD

**Issue by ocdi** [appscode/voyager#1161]
I'm new to kubernetes and wanting to use haproxy and thought I would try out the voyager product. It looks really good. I am currently manually configuring haproxy on our old servers and wanting to move to a nice new kubernetes / container world. I had it up and running all OK, with SSL certificate working through the ingres.

I was attempting to expose the node stats when the operator container started crashing. 

The partial configuration I added was adding the annotations from the docs/example
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
```
I am using Azure and this is the stack trace, if that helps. I'm unsure where to go next. It was working well until I got to this point.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4eaab2]
 goroutine 336 [running]:
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x211e200, 0x41443a0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
io/ioutil.readAll.func1(0xc420b2ab78)
	/usr/local/go/src/io/ioutil/ioutil.go:30 +0x111
panic(0x211e200, 0x41443a0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
bytes.(*Buffer).ReadFrom(0xc420b2aad0, 0x0, 0x0, 0xc420b5b800, 0x0, 0x200)
	/usr/local/go/src/bytes/buffer.go:209 +0x142
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x12c
io/ioutil.ReadAll(0x0, 0x0, 0x0, 0xc420b2ad18, 0xaf42cf, 0xc42004cd80, 0x3f96860)
	/usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e
github.com/appscode/voyager/third_party/forked/cloudprovider/providers/azure.NewCloud(0x0, 0x0, 0x7ffe747ee4be, 0x5, 0xc42023dd00, 0xc400000001)
	/go/src/github.com/appscode/voyager/third_party/forked/cloudprovider/providers/azure/azure.go:71 +0x6d
github.com/appscode/voyager/third_party/forked/cloudprovider.GetCloudProvider(0x7ffe747ee4be, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/appscode/voyager/third_party/forked/cloudprovider/plugins.go:85 +0xda
github.com/appscode/voyager/third_party/forked/cloudprovider.InitCloudProvider(0x7ffe747ee4be, 0x5, 0x7ffe747ee4c6, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/appscode/voyager/third_party/forked/cloudprovider/plugins.go:111 +0x4b3
github.com/appscode/voyager/pkg/ingress.NewNodePortController(0x3fb1d20, 0xc420f86f60, 0x3fc4320, 0xc4206ba1e0, 0x3f87da0, 0xc42081aee0, 0x3f988a0, 0xc420705550, 0x3f9fda0, 0xc420705400, ...)
	/go/src/github.com/appscode/voyager/pkg/ingress/nodeport.go:73 +0x3ea
github.com/appscode/voyager/pkg/ingress.NewController(0x3fb1d20, 0xc420f86f60, 0x3fc4320, 0xc4206ba1e0, 0x3f87da0, 0xc42081aee0, 0x3f988a0, 0xc420705550, 0x3f9fda0, 0xc420705400, ...)
	/go/src/github.com/appscode/voyager/pkg/ingress/controller.go:75 +0x5ff
github.com/appscode/voyager/pkg/operator.(*Operator).reconcileEngress(0xc4205ce380, 0xc4208d13c0, 0x17, 0xc420f8fda0, 0x72dc00)
	/go/src/github.com/appscode/voyager/pkg/operator/ingress_crds.go:83 +0x396
github.com/appscode/voyager/pkg/operator.(*Operator).(github.com/appscode/voyager/pkg/operator.reconcileEngress)-fm(0xc4208d13c0, 0x17, 0xc420836300, 0x1fbda00)
	/go/src/github.com/appscode/voyager/pkg/operator/ingress_crds.go:23 +0x3e
github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue.(*Worker).processNextEntry(0xc42080a840, 0x85cd00)
	/go/src/github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue/worker.go:68 +0xeb
github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue.(*Worker).processQueue(0xc42080a840)
	/go/src/github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue/worker.go:51 +0x2b
github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue.(*Worker).(github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue.processQueue)-fm()
	/go/src/github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue/worker.go:37 +0x2a
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4206411c0)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4206411c0, 0x3b9aca00, 0x0, 0x1, 0xc42005a660)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4206411c0, 0x3b9aca00, 0xc42005a660)
	/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue.(*Worker).Run
	/go/src/github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/queue/worker.go:37 +0x90
```

I tried removing the annotations but it looks dead.

```Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"ingress.appscode.com/stats":null,"ingress.appscode.com/type":null,"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"voyager.appscode.com/v1beta1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{},\"name\":\"cluster-ingress\",\"namespace\":\"default\"},\"spec\":{\"nodeSelector\":{\"beta.kubernetes.io/os\":\"linux\"},\"rules\":[{\"host\":\"alpqldtest2.ml.net.au\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"alpqld\",\"servicePort\":\"443\"}}]}},{\"host\":\"alpqldtest.ml.net.au\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"alpqld\",\"servicePort\":\"443\"}}]}}],\"tls\":[{\"hosts\":[\"alpqldtest.ml.net.au\"],\"ref\":{\"kind\":\"Certificate\",\"name\":\"alpqldtest\"}}]}}\n"}},"spec":{}}to:&{0xc04208d740 0xc04236e8c0 default cluster-ingress .\cluster-ingres.yml 0xc042094958 40497 false}for: ".\\cluster-ingres.yml": Internal error occurred: failed calling admission webhook "admission.voyager.appscode.com": the server is currently unable to handle the request
```

**Comment by tamalsaha** [comment]
Are you using AKS? What is your `kubectl version` ?

**Comment by ocdi** [comment]
I setup a new cluster and went direct to those attributes. I believe the annotation ```ingress.appscode.com/type: 'NodePort'```

Is actually completely separate to the stats, right? I added a new ingress directly and it worked fine, but didn't create a load balancer. I removed the above annotation and then it changed to a `LoadBalancer`

I think this is partly my stupidity, and I think the bug might present if you add the NodePort as a type, where a pre-existing LoadBalancer has been assigned.

**Comment by tamalsaha** [comment]
You can't change the `ingress.appscode.com/type` annotation on an Ingress. If you want to change it, then you have to delete the ingress and recreate with the correct `ingress.appscode.com/type` annotation .

**Comment by tamalsaha** [comment]
@ocdi , does https://github.com/appscode/voyager/pull/1166 fixes this issue?

**Comment by ocdi** [comment]
@tamalsaha Ah, no, it was a related issue I faced when getting it setup but not the cause of the crash.

I thought I had actually commented yesterday on this. Given the annotation isn't supposed to be changed, ultimately it was my mistake. How you recover from that? When I tried to `kubectl apply` my ingres definition, I had the webhook failed because operator wasn't running.

Ideally the operator shouldn't crash when people do stupid things, like I did. :-)

I am happy for you to close this as user error, but I think it would be worth being more graceful.

**Comment by tamalsaha** [comment]
We will check. Just to be clear, was the operator already broken because it was lacking that node-selector annotation ?

**Comment by ocdi** [comment]
The full timeline was:

1) Attempt to install voyager
2) The install script timed out
3) Manually edit the YAML definition of the voyager-operator to add the node selector
4) Things working well... able to define an Ingres and SSL certs and all was looking good

Later I was playing, and thought I would try adding the stats annotation

I modified the ingres definition by adding the two `NodePort` and `Stats` annotations (the sample I found must have had them together). I thought NodePort was related to how the Stats were exposed, without realising I was attempting to modify the Load Balancer definition itself.

As soon as I applied that the voyager-operator pod started crashing with the earlier stack trace.

**Comment by tamalsaha** [comment]
Ok. We should make the change of ingress type a validation error.

**Comment by tamalsaha** [comment]
@ocdi , one thing I would like to clarify is that `acs-engine` does not support NodePort and HostPort mode.

**Comment by ocdi** [comment]
To be honest I have no idea, is that the cause of the crash because it isn't actually possible to be done? I am very new to kubernetes sorry I'm not sure.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/voyager/releases/tag/7.3.0
