### ISSUE TITLE
Upgrade HAProxy 

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#1173]
HAProxy 1.8.9 only when using resolver https://github.com/docker-library/haproxy/issues/67

Reported by DenTer on our slack: https://appscode.slack.com/archives/C0XQFLGRM/p1530522934000241

**Comment by KresoDenis** [comment]
Im Denter. I tried localy 1.8.12 and 1.8.8 in docker compose and it worked without 100% cou. 1.8.9 specific bug i guess. 

And ultimately i used older image on kubernetes voyager.
--haproxy-image-tag=1.8.8-7.0.0-alpine

as temporary solution.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/voyager/releases/tag/7.3.0 release.
