### ISSUE TITLE
Drain a backend in terminating status?

### ISSUE THREAD

**Issue by dcowden** [appscode/voyager#1196]
We have a legacy application ( tomcat/java), which needs sticky sessions. When we deploy new versions of our applications, we need to stop sending new connections to a server, while sending bound sessions to the old server. Please note: this is not referring to in-flight requests, we're needing the active tomcat sessions to expire, which normally takes a few hours.

This is possible using haproxy drain command. This will send bound connections to the old server, but send new ones elsewhere. 

When kubernetes terminates a pod, it enters the TERMINATING status. When sticky sessions are enabled, the desired functionality is usually to put the associated pod into drain mode.  This is nice because it allows the application preStop hooks to decide when its ready to stop. When the preStop hook terminates, the pod dies, and bound sessions end.

How could we accomplish this flow using voyager? We are currently using [jcmoraisjr/haproxy-ingress](https://github.com/jcmoraisjr/haproxy-ingress), because it meets this requirement. ( In fact, the developers there were kind enough to add this feature.  I'm sure [their implementation](https://github.com/jcmoraisjr/haproxy-ingress/pull/95) could be ported, presuming no licensing issues exist.

**Comment by tamalsaha** [comment]
Slack conv: https://kubernetes.slack.com/archives/C09NXKJKA/p1531791934000094

**Comment by dcowden** [comment]
@tamalsaha is there any changes since last year that would enable drain mode?

I'm not seeing anything that has been added.  If there is not direct support, could it be possible to accomplish the flow via http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-agent-check?

**Comment by gavinbunney** [comment]
Hi @kfoozminus & @tamalsaha - we have the same requirements as @dcowden to support terminating pod draining (java/tomcat - hurray!). I see this issue was added to the v10.1.0 milestone last week - so it still planned on being in the next release? Is so that would be 💯 !
