### ISSUE TITLE
Support Internal Load Balancer Type

### ISSUE THREAD

**Issue by RisingPhorce** [appscode/voyager#1197]
A Kubernetes Service of type Load Balancer running in aws and using the annotation "service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0" will create a classic elb with the internal load balancer option and no public IP.

https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-2

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-internal-load-balancers.html?icmpid=docs_elb_console

For our use case we are creating some Kubernetes services that are only accessed from the Kubernetes VPC (or peered VPC). 

Maybe there is voyager config that allows this but I couldn't find it.  If not, would you consider supporting this configuration?

Thanks.

**Comment by tamalsaha** [comment]
Can you use `service-annotations` to pass this to the voyager-<ing> service ? https://github.com/appscode/voyager/blob/master/docs/guides/ingress/configuration/service-annotations.md

**Comment by RisingPhorce** [comment]
Oops!  I should have caught that!  Worked perfectly!

Thanks for the quick reply.  

Excellent work by the way, Voyager is a great project!

**Comment by tamalsaha** [comment]
Thanks for using Voyager. Happy to help!
