### ISSUE TITLE
Potential Issue With VOYAGER_* Environment Variables

### ISSUE THREAD

**Issue by RisingPhorce** [appscode/voyager#1224]
Voyager injects environment variables describing IPs, Hosts and Ports for ingress frontends.  As an example for Service xyz and fronted in Voyager with an http frontend redirecting port 80 to frontend 443 Voyager injects these environment variables into (all ?) pods:

VOYAGER_XYZSVC_PORT=tcp://100.0.0.1:443
VOYAGER_XYZSVC_PORT_443_TCP=tcp://100.0.0.1:443
VOYAGER_XYZSVC_PORT_443_TCP_ADDR=100.0.0.1
VOYAGER_XYZSVC_PORT_443_TCP_PORT=443
VOYAGER_XYZSVC_PORT_443_TCP_PROTO=tcp
VOYAGER_XYZSVC_PORT_80_TCP=tcp://100.0.0.1:80
VOYAGER_XYZSVC_PORT_80_TCP_ADDR=100.0.0.1
VOYAGER_XYZSVC_PORT_80_TCP_PORT=80
VOYAGER_XYZSVC_PORT_80_TCP_PROTO=tcp
VOYAGER_XYZSVC_SERVICE_HOST=100.0.0.1
VOYAGER_XYZSVC_SERVICE_PORT=443
VOYAGER_XYZSVC_SERVICE_PORT_TCP_443=443
VOYAGER_XYZSVC_SERVICE_PORT_TCP_80=80

Because voyager creates an elb per voyager ingress, I am trying to use a design that put one voyager ingress in front of each type of service which may have many different service deployments.  This should keep the number of elbs down to a predictable and stable number.  

However I am concerned about how many env vars are going to be injected into pods and furthermore weather this leaks information about other pods to an attacker that is able to execute commands in a compromised container.

**Comment by tamalsaha** [comment]
These environment variables are injected by Kubernetes. See here: https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services

I don't think there is a way to disable this behavior.
