### ISSUE TITLE
TCP SNI doesn't seem to work

### ISSUE THREAD

**Issue by harrison-tarr** [appscode/voyager#1247]
I followed the instructions on here: https://appscode.com/products/voyager/7.4.0/guides/ingress/tcp/tcp-sni/ (substituting my hosts/pods for the ones in the example) 
but when i try to access my pods, it always directs me to the first one

**Comment by diptadas** [comment]
Hi @harrison-tarr, can you share your Ingress and generated ConfigMap?

**Comment by diptadas** [comment]
Hi @harrison-tarr, we have tested tcp-sni with voyager `v8.0.1` and didn't face such issue. Please reopen if you are still having this issue.
