### ISSUE TITLE
Stuck at deletion - finalizers:  voyager.appscode.com

### ISSUE THREAD

**Issue by rzal** [appscode/voyager#1249]
Images
appscode/voyager:7.1.1
appscode/haproxy:1.8.9-7.1.1-alpine

Half of my attempts to delete a voyager ingress get stuck.

  finalizers:
  - voyager.appscode.com
  - foregroundDeletion

I am using Azure. Is Voyager waiting for the LB IP to be released, but Azure fails to respond?

Thanks

**Comment by tshak** [comment]
I've been investigating the same symptoms in AWS. We run integration tests where we create an ingress, wait for the LB and service to be available, and tear it down. Even after waiting multiple hours the ingress pod is stuck in the terminating state. The only way to delete the pod is with `--force --grace-period=0`

Operator: `appscode/voyager:7.2.0`
Haproxy: `1.8.9-7.2.0-alpine`
Kubernetes: `v1.10.3`

I can repro this manually with a simple ingress+service (maybe the service isn't even necessary): https://gist.github.com/tshak/e410fc5bad89b1d0b7371dfca4a681b6

I went through the operator logs and filtered out the lines around the deletion: 
```
I1001 12:45:37.189304       1 ingress_crds.go:87] Delete for engress default/repro
I1001 12:45:37.235876       1 delete.go:10] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting ConfigMap default/voyager-repro
I1001 12:45:37.258428       1 endpoints.go:36] Sync/Add/Update for Endpoints default/voyager-repro
I1001 12:45:37.261592       1 rbac.go:181] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting RoleBinding default/voyager-repro
W1001 12:45:37.264684       1 configmaps.go:24] ConfigMap default/voyager-repro does not exist anymore
I1001 12:45:37.285410       1 rbac.go:188] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting Role default/voyager-repro
I1001 12:45:37.289462       1 endpoints.go:36] Sync/Add/Update for Endpoints default/voyager-repro
I1001 12:45:37.300468       1 rbac.go:195] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting ServiceAccount default/voyager-repro
I1001 12:45:37.319050       1 delete.go:19] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting Service default/voyager-repro
W1001 12:45:37.347753       1 services.go:29] Service default/voyager-repro does not exist anymore
E1001 12:45:37.412368       1 loadbalancer.go:242] [64af04bf-3c0f-4073-8ac9-7664718460c8] [failed to get stat service voyager-repro-stats, reason: services "voyager-repro-stats" not found]
I1001 12:45:37.412399       1 delete.go:28] [64af04bf-3c0f-4073-8ac9-7664718460c8] Deleting Stats Service default/voyager-repro-stats
I1001 12:45:37.415114       1 ingress.go:56] Patching Ingress default/repro with {"metadata":{"finalizers":null}}.
I1001 12:45:37.419835       1 wrap.go:42] POST /apis/admission.voyager.appscode.com/v1beta1/admissionreviews: (786.768µs) 201 [[Go-http-client/2.0] 100.126.208.128:30414]
```
 
 Please let me know if you need additional help debugging.

**Comment by tamalsaha** [comment]
For NodePort type Ingresses, Voyager can open firewall ports. To make sure that those Firewalls to closed when Ingress in deleted, we use finalizer on the ingress. 
https://github.com/appscode/voyager/blob/master/pkg/ingress/nodeport.go#L292

Now, this means that when an Ingress object is removed, the voyager operator must be running, as it will peform the finalizer actions. From the log above, we can see that  the finalizer was removed by the operator,

```
I1001 12:45:37.415114       1 ingress.go:56] Patching Ingress default/repro with {"metadata":{"finalizers":null}}.
```

So, Kubernetes should be able to collect that Ingress object. 

Can you show me the output of `kubectl describe` command for Ingress pods? Those should be deleted when the Deployment for Ingress objects is deleted.

**Comment by tshak** [comment]
In our case the ingress used as an isolated repro is in the aforementioned gist (https://gist.github.com/tshak/e410fc5bad89b1d0b7371dfca4a681b6). The operator was running and we are able to successfully create other ingresses just fine. 

I went through a quick repro again, and I noticed something strange with the pods. Note that this is a single replica (default) deployment:

After kubectl apply -f repro.yml
```
voyager-repro-5c65d99685-r2j5p   1/1       Running   0          5s
```
After kubectl delete -f repro.yml
```
voyager-repro-5c65d99685-f84xr   0/1       ContainerCreating   0          2s
voyager-repro-5c65d99685-r2j5p   0/1       Terminating         0          13s
```
After 5 minutes... (verified ELB is deleted in AWS)
```
voyager-repro-5c65d99685-f84xr   0/1       Terminating   0          5m
```
Note the ID of the stuck pod - is not the original pod, but one that was created after attempting to delete the ingress. Here's the description of the stuck pod: https://gist.github.com/tshak/2bda042e2705e7f1fc43719eb306da08

**Comment by tamalsaha** [comment]
`list of unattached volumes=[voyager-certdir voyager-repro-token-4bgsz]` .

From the log, the volumes could not unmounted and so pods were not deleted? Can you check the `kube-controller-manager` log and `kubelet` log on the node where this pod is running to see what the log says?

**Comment by tamalsaha** [comment]
Also, why does it try to recreate pod when Ingress is deleted?

**Comment by tshak** [comment]
> Also, why does it try to recreate pod when Ingress is deleted?
No idea :). This is the first time I noticed this and thought it was quite strange.

**Comment by tshak** [comment]
I will have to repro again in order to get logs, will hopefully get that to you by EOD

**Comment by tshak** [comment]
I repro'd again and did not see anything out of the ordinary in either log during the repro timeframe.

**Comment by tshak** [comment]
Maybe this is something: ```Orphaned pod "5ae84375-b5cf-11e8-9d29-0664d33a443a" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.```

**Comment by tamalsaha** [comment]
https://github.com/appscode/voyager/pull/1315 should improve this.

**Comment by tamalsaha** [comment]
Please reopen if you are still having this issue.
