### ISSUE TITLE
Unavailable services get removed from HAProxy configuration

### ISSUE THREAD

**Issue by blop** [appscode/voyager#1285]
Hello guys,

It seems that voyager omits the definition of the backend completely when there is no replica running.
That sounds like a good optimisation but it has some side effects.

Because the whole backend is removed from the HAProxy configuration, there is no "use_backend" rule anymore in the frontend, and the requests might get routed to another backend instead (like the default backend or another path rule).

Seems to be related to pkg/ingress/parser.go:455 : 
```
				} else if len(bk.Endpoints) == 0 {
					c.recorder.Eventf(
						c.Ingress.ObjectReference(),
						core.EventTypeWarning,
						eventer.EventReasonBackendInvalid,
						"spec.rules[%d].http.paths[%d] skipped, reason: %s", ri, pi, "endpoint not found",
					)

```

You can reproduce this easily with 3 services : 
/foo/* gets routed to foo
/bar/* gets routed to bar
/* gets routed by default to another one

If you scale the replicas of foo to 0 (or if it's not fully deployed), the requests for /foot/something will end up getting served by the default service, which will result in a 404 instead of a 503 HTTP error.

I think that this behaviour should be changed, or that there should be at least some flag to keep backend definition even if the service is not ready.

It seems strange to allow traffic to go to another path rule or ti the default backend based on the service availability.

Thanks !

**Comment by tamalsaha** [comment]
Fixed.
