### ISSUE TITLE
unsupported LBType LoadBalancer

### ISSUE THREAD

**Issue by maaeps** [appscode/voyager#1297]
Hi there,
applying an ingress doesn't work for me.
After some time haproxy gets deployed. (Is it normal that this takes some time?)
But it's not getting ready.
kubectl describe ingress.voyager.appscode.com ingressname outputs:
`Warning  IngressInvalid                 9m55s  voyager operator  Reason: ingress namespace/ingressname uses unsupported LBType LoadBalancer for cloud provider`
I hope someone can help me.
Maximilian

**Comment by rzal** [comment]
I'm getting the same now with:

`provider=azure helm install appscode/voyager --name voyager-operator --version 9.0.0 --set cloudProvider=$provider
`

**Comment by alexkreidler** [comment]
I've been getting this on EKS

**Comment by mausspb** [comment]
Same on GKEm helm version 11.0.1
