### ISSUE TITLE
appscode/oauth2_proxy:2.3.0 is broken

### ISSUE THREAD

**Issue by endrec** [appscode/voyager#1300]
The [example](https://github.com/appscode/voyager/blob/master/docs/guides/ingress/security/oauth-google.md) in the oauth integration guide refers to the  `appscode/oauth2_proxy:2.3.0` image, which seems to be broken:

```
$ docker run appscode/oauth2_proxy:2.3.0
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

**Comment by tamalsaha** [comment]
@endrec , please try `appscode/oauth2_proxy:2.3.1` . We are now building static binary and should fix this issue.

**Comment by endrec** [comment]
2.3.1 works, thank you very much.

**Comment by tamalsaha** [comment]
Thanks for reporting the issue.
