### ISSUE TITLE
Oauth2_Proxy is dead, long live Oauth2_Proxy

### ISSUE THREAD

**Issue by endrec** [appscode/voyager#1302]
The original oauth2_proxy project is abandoned: https://github.com/bitly/oauth2_proxy/issues/628#issuecomment-417121636
Pusher has decided to take on the project officially (https://github.com/pusher/oauth2_proxy/pull/7), so Voyager should move over to the new fork when they are ready.

**Comment by tamalsaha** [comment]
Yes. We have one extra commit in our fork that needs to be upstream before we can start using Pusher's fork. 
https://github.com/appscode/oauth2_proxy/commit/14f5597ececbf9054fbda906598739cc058e1fba

It is not clear when we will have bandwidth to deal with that. If you are interested in helping out, you are most welcome. 

On a separate note, I recently saw https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-2-authentication/ . It will be interesting to see how does that work.

**Comment by endrec** [comment]
That is definitely an interesting article. For me it seems that solution is more suitable when you have control over the key used to sign the JWT tokens. It does not seem easy to setup with external providers.

**Comment by tamalsaha** [comment]
Fixed
