### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by liyongxian** [appscode/voyager#1319]
Hi
   When I access URL of static NodePort,I meet a problem,**"503 Service Unavailable"**.
**k8s:**
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
**How to install**
  helm install appscode/voyager --name voyager-operator --version 8.0.1
**voyager env**
voyager-voyager-operator-6bdfc47888-8hvlv   1/1     Running   0          73m
nginx-7b49ff856d-nplpb                  1/1     Running   0          69m
voyager-test-ingress-5f5889db86-btrr9   1/1     Running   0          46m
**ingress**
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/use-node-port: "true"
    ingress.appscode.com/type: NodePort
spec:
  rules:
  - host: lyx.nginx.com
    http:
      nodePort: 32068
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /nginx
**Result**
http://192.168.2.45:32068/nginx

**Service nginx**
kubectl describe svc nginx

Name:              nginx
Namespace:         default
Labels:            app.kubernetes.io/instance=nginx
                   app.kubernetes.io/managed-by=Tiller
                   app.kubernetes.io/name=nginx
                   helm.sh/chart=nginx-0.1.0
Annotations:       <none>
Selector:          app.kubernetes.io/instance=nginx,app.kubernetes.io/name=nginx
Type:              ClusterIP
IP:                10.100.250.182
Port:              http  80/TCP
TargetPort:        http/TCP
Endpoints:         10.244.2.52:80
Session Affinity:  None
Events:            <none>

**Problem:**
   503 Service Unavailable
   No server is available to handle this request.

**Comment by diptadas** [comment]
Hi @liyongxian, did you specify the host header in your request?
For example:
`curl -v -H 'Host: lyx.nginx.com' 192.168.2.45:32068/nginx`

**Comment by tamalsaha** [comment]
Please reopen if you are still having this issue.
