### ISSUE TITLE
Do not sort ALPN options

### ISSUE THREAD

**Issue by diptadas** [appscode/voyager#1327]
https://github.com/appscode/voyager/blob/master/apis/voyager/v1beta1/diff.go#L293
https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#alpn

> If both HTTP/2 and HTTP/1.1 are expected to be supported, both versions can be advertised, in order of preference.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/appscode/voyager/pull/1328
