### ISSUE TITLE
Disable onessl analytics when voyager analytics is disabled

### ISSUE THREAD

**Issue by frozenice** [appscode/voyager#1332]
I skimmed the installer script (`hack/deploy/voyager.sh`) and noticed it uses [onessl](https://github.com/kubepack/onessl). The README of which states:
> onessl binary collects anonymous usage statistics to help us learn how the software is being used and how we can improve it. To disable stats collection, run the operator with the flag --analytics=false.

Your README also states:
> Voyager binaries collects anonymous usage statistics to help us learn how the software is being used and how we can improve it. To disable stats collection, run the operator with the flag --enable-analytics=false.

I suggest also disabling the analytics feature of onessl, if `--enable-analytics=false` is passed to the script. That's what I expect when I tell a software not to do analytics.

P.S.: I am new to both voyager and onessl. This was one of the first things I noticed, besides that voyager might be a good fit for my needs. I'll give it a try soon. :)

**Comment by tamalsaha** [comment]
We are interested in usage number of anything we consider a "product". onessl is not a product per se, it is just an installer helper. So, I have removed analytics collection from onessl 0.10.0 and updated Voyager installer script to use the new version. This should resolve this issue.

**Comment by tamalsaha** [comment]
https://github.com/appscode/voyager/releases/tag/9.0.0 release includes the fix.
