### ISSUE TITLE
Memory and CPU requests for Daemonset?

### ISSUE THREAD

**Issue by mcasperson** [appscode/voyager#1335]
Is there any way to define the CPU and memory requests for pods created by the Voyager Daemonset?

We have a situation where the pods that get placed on a node fill it up quite completely, and because the Voyager pods don't have any requests set, they appear to be starved of CPU time.

I can patch the Daemonset with:
```
kubectl patch daemonset voyager-myapp-ingress --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/resources/requests", "value": {"cpu": "100m", "memory": "64Mi"}}]'
```

and delete and recreate the pods, which solves the issue. But it does mean I have to be careful about patching the Daemonset after it is created. Using annotations on the Ingress would be a more robust solution if it is available.

**Comment by tamalsaha** [comment]
Yes. You can specify it in the `spec.resources` field in ingress yaml
https://github.com/appscode/voyager/blob/master/apis/voyager/v1beta1/ingress.go#L88

Please reopen if not answered.
