### ISSUE TITLE
Cannot use voyager/client with client-go collision with vendored packages

### ISSUE THREAD

**Issue by mikefaraponov** [appscode/voyager#1356]
apimachinery from local vendor collides with apimachinery of voyager vendor

**Comment by tamalsaha** [comment]
What version of k8s.io/client-go package are you using?

**Comment by mikefaraponov** [comment]
v9.0.0

**Comment by tamalsaha** [comment]
What version of Voyager are you trying to use?

**Comment by mikefaraponov** [comment]
latest, it was 9.0.0. I rechecked it's more correctly to say that apimachinery has a collision with one used in voyager "ac-1.13.0", that's why I cannot use voyager clientset and dependent resources such as intstr and others

**Comment by tamalsaha** [comment]
Yeah. So, you need to match Voyager version with k8s.io/client-go, etc version. As long as those versions match, there should be no issue.

For example,
k8s.io/client-go 9.x.x will work with Voyager 9.x.x
k8s.io/client-go 10.x.x will work with Voyager master. We are going to cut Voyager 10.0.0 from master.

Please reopen if you are still having any issue.
