### ISSUE TITLE
Upgrade to HAProxy 1.9.5

### ISSUE THREAD

**Issue by blop** [appscode/voyager#1362]
I suggest updating HAProxy, with all the fixed listed here :

1.9.3:
https://www.mail-archive.com/haproxy@formilux.org/msg32626.html

1.9.4:
https://www.mail-archive.com/haproxy@formilux.org/msg32716.html

1.9.5:
https://www.mail-archive.com/haproxy@formilux.org/msg33056.html

**Comment by tamalsaha** [comment]
Thanks @blop ! You are welcome to send a pr, if you like. See the 1.9.2 and 1.9.2-alpine folders here: https://github.com/appscode/voyager/tree/master/hack/docker/haproxy

Just copy those folders and build a 1.9.4 and 1.9.4-alpine folders. That's it. We are happy to review and merge after e2e checks.
