### ISSUE TITLE
Custom LUA scripts support

### ISSUE THREAD

**Issue by cober** [appscode/voyager#1370]
I am not able to find if Voyager currently supports adding LUA scripts.

Is there a way to do it so far?

We have one idea of editing a template file and adding a line of load lua script under "global" config section, but the issue is that we need somehow to inject it voyager operator. Dirty fix would be something like that:

```      volumeMounts:
      - name: lua-script
        mountPath: /etc/lua-script.lua
        subPath: lua-script.lua

**Comment by diptadas** [comment]
Hi @cober you can use `spec.configVolumes` to inject additional configuration files.
Ref: https://github.com/appscode/voyager/blob/master/docs/guides/ingress/configuration/config-volumes.md

**Comment by cober** [comment]
Thanks @diptadas, I will use this for reference.
