### ISSUE TITLE
Voyager 10 fails to deploy with Helm installer

### ISSUE THREAD

**Issue by tlvenn** [appscode/voyager#1400]
Hi,

I am trying to install Voyager 10 with the helm chart but the deployment is failing. When i look at the log of the operator, i see the following:

```
I0529 04:25:12.474642       1 run.go:26] Starting voyager...
I0529 04:25:12.848926       1 lib.go:112] Kubernetes version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
I0529 04:25:12.863378       1 operator.go:107] Ensuring CRD registration
```

So it seems the operator is waiting endlessly on the `Ensuring CRD registration`.

Only 2 values are set for this chart on my side:
```
cloudProvider: baremetal
ingressClass: voyager
```

Any idea why this is happening ?
On a side note, I can deploy voyager with the script just fine.

**Comment by devteng** [comment]
I am having the same issue stuck at Ensuring CRD registration

helm repo add appscode https://charts.appscode.com/stable/
helm repo update

helm upgrade --install \
  voyager-ingress appscode/voyager \
	--namespace kube-system \
	--tiller-namespace kube-system \
  --debug \
  --set rbac.create=true \
  --set cloudProvider=aks \
  --set replicaCount=3 \
  --set criticalAddon=true \
  --set enableAnalytics=false \
  --wait

**Comment by tamalsaha** [comment]
@devteng , please try without the `--wait` flag.

**Comment by tamalsaha** [comment]
@tlvenn, can you please share the exact command you used to deploy Voyager?

**Comment by tlvenn** [comment]
I am using Terraform to setup voyager but it translates to:
```
helm upgrade --install voyager-ingress appscode/voyager
--set cloudProvider=baremetal
--set ingressClass=voyager
--set enableAnalytics=false
```

**Comment by ajchiarello** [comment]
I see the same issue, but I noticed that if I scale the deployment to 0 replicas and then back to one, the newly created pod starts normally.

**Comment by blasrodriguez** [comment]
Experiencing the same issue with voyager 11

**Comment by tamalsaha** [comment]
Please try the new version https://github.com/appscode/voyager/releases/tag/v12.0.0-rc.0. This should be fixed.

**Comment by xcompass** [comment]
I'm getting the same error on 12.0.0-rc.0. I had to delete the operator `helm delete` and re-install to work around it. After it successfully started, the logs show the following:
```
I0316 22:41:57.001201       1 operator.go:124] Ensuring CRD registration
E0316 22:42:00.145426       1 nodes.go:57] <nil>
E0316 22:42:00.146525       1 nodes.go:57] <nil>
E0316 22:42:00.146552       1 nodes.go:57] <nil>
E0316 22:42:00.146561       1 nodes.go:57] <nil>
E0316 22:42:00.146568       1 nodes.go:57] <nil>
E0316 22:42:00.146574       1 nodes.go:57] <nil>
E0316 22:42:00.146581       1 nodes.go:57] <nil>
E0316 22:42:00.146589       1 nodes.go:57] <nil>
E0316 22:42:00.146602       1 nodes.go:57] <nil>
E0316 22:42:00.146634       1 nodes.go:57] <nil>
E0316 22:42:00.146652       1 nodes.go:57] <nil>
E0316 22:42:00.146660       1 nodes.go:57] <nil>
E0316 22:42:00.146665       1 nodes.go:57] <nil>
E0316 22:42:00.146693       1 nodes.go:57] <nil>
E0316 22:42:00.146711       1 nodes.go:57] <nil>
```
