### ISSUE TITLE
Document non-modifiable ingress annotations

### ISSUE THREAD

**Issue by sadlil** [appscode/voyager#143]
Currently the following annotations for an ingress are not modifiable.
```
ingress.appscode.com/type
ingress.appscode.com/daemon.nodeSelector
ingress.appscode.com/persist
ingress.appscode.com/ip
```

**Comment by TamalSaha** [comment]
@sadlil what about `ingress.appscode.com/ip` ?

**Comment by sadlil** [comment]
updated. thnx @TamalSaha

**Comment by TamalSaha** [comment]
There is no plans to support updates for these annotations. To update these events, first delete the current ingress, then recreate with the correct annotations.
