### ISSUE TITLE
Helm Chart v11.0.0 errors on install

### ISSUE THREAD

**Issue by ajchiarello** [appscode/voyager#1433]
When attempting to upgrade from the 10.0.0 Helm chart to the v11.0.0 Helm chart, I get the following error:

> Error: rpc error: code = Unknown desc = parse error in "voyager/templates/cluster-role.yaml": template: voyager/templates/cluster-role.yaml:89: unexpected {{end}}

Looks like an error in the template

**Comment by alexpirine** [comment]
Last two releases have templating errors? Do you need some advice on CI?

**Comment by alexpirine** [comment]
Just upgrade to https://traefik.io/ instead

**Comment by alexpirine** [comment]
> When attempting to upgrade from the 10.0.0 Helm chart to the v11.0.0 Helm chart, I get the following error:
> 
> > Error: rpc error: code = Unknown desc = parse error in "voyager/templates/cluster-role.yaml": template: voyager/templates/cluster-role.yaml:89: unexpected {{end}}
> 
> Looks like an error in the template

@ajchiarello 
You might just upgrade to https://traefik.io/ instead 😄— [they have a Helm chart too](https://github.com/helm/charts/tree/master/stable/traefik).
