### ISSUE TITLE
Helm Chart v11.0.1 errors on install

### ISSUE THREAD

**Issue by ajchiarello** [appscode/voyager#1438]
When attempting to upgrade to the 11.0.1 version of the helm chart, I receive the following error:

> helm upgrade voyager appscode-stable/voyager --set cloudProvider=metallb
UPGRADE FAILED
Error: YAML parse error on voyager/templates/deployment.yaml: error converting YAML to JSON: yaml: line 82: mapping values are not allowed in this context
Error: UPGRADE FAILED: YAML parse error on voyager/templates/deployment.yaml: error converting YAML to JSON: yaml: line 82: mapping values are not allowed in this context

**Comment by killerham** [comment]
I'm having this as well

**Comment by nterry** [comment]
@the fix is simple
https://github.com/appscode/voyager/blob/v11.0.1/chart/voyager/templates/deployment.yaml#L128

Change it to {{- end }} (the second minus is removed) This is a tricky little beast. The templating engine considers newlines as whitespace and helpfully removes it for you.

**Comment by hengel2810** [comment]
I'm troubling with the same problem. Do you already have an idea when you are releasing a new version ?

**Comment by alexpirine** [comment]
Having the same issue…

AppsCode team: are you publishing releases without testing?

I'm a bit doubtful here… Should we use it in production or should we switch to something else?

**Comment by isavcic** [comment]
Confirming that #1441 fixes the issue.

**Comment by nicklasfrahm** [comment]
Any estimate when the helm chart in the `appscode` repository will be updated?

**Comment by derverzweifler** [comment]
Please publish the fixed version to helm repo as the chart is pretty much unusable atm.

**Comment by gurrish** [comment]
Also having this issue!

**Comment by tamalsaha** [comment]
Please try the new release https://github.com/appscode/voyager/releases/tag/v12.0.0-rc.0 . This should be fixed now.
