### ISSUE TITLE
Voyager with GKE HTTP(S) -L7 Load balancer

### ISSUE THREAD

**Issue by git4suvendu** [appscode/voyager#1453]
Hello,

I am running a an application in GKE Cluster and using Voyager as a ingress controller. Whenever I create an ingress resource, it creates a TCP regional loadbalancer which is L4.

How can I create L7 HTTP(s) Global load balancer using Voyager? Or Voyager does not support L7 loadbalancer?

Thanks,
Suvendu

**Comment by tamalsaha** [comment]
Voyager does not support L7 loadbalancer. There is no plan to add support for this.
