### ISSUE TITLE
Disable analytics when running tests

### ISSUE THREAD

**Issue by TamalSaha** [appscode/voyager#147]
`--analytics=false`

**Comment by sadlil** [comment]
@ashiquzzaman33  add --analytics=false in the voyager-operator yaml.

**Comment by TamalSaha** [comment]
We can't add it directly in the YAML. Then it will be disabled for everyone by default. Our Jenkinsfile needs to dynamically disable this. One option can be that it can be disabled via ENV variable.

**Comment by sadlil** [comment]
> Jenkinsfile needs to dynamically disable this
yes

**Comment by TamalSaha** [comment]
https://jenkins.io/doc/book/pipeline/shared-libraries/#using-third-party-libraries
```
@Grab(group='org.yaml', module='snakeyaml', version='1.13') 
```
https://stackoverflow.com/questions/35521788/snakeyaml-by-example

Docs:
https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-tutorial

**Comment by TamalSaha** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-26192

**Comment by TamalSaha** [comment]
POJOs for Kubernetes objects thanks to Fabric8 http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.fabric8%22%20AND%20a%3A%22kubernetes-model%22

These are auto-generated from protos.

**Comment by TamalSaha** [comment]
Current plan: Add a `Global Shared lib` in repo https://github.com/appscode-ci/pipeline-shared-lib . 

It will have 2 methods:

Marshal(): KuberObject POJO -> String
Unmarshal() : String -> KubeObject POJO

POJOs for Kubernetes objects thanks to Fabric8 http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.fabric8%22%20AND%20a%3A%22kubernetes-model%22

These are auto-generated from protos.
