### ISSUE TITLE
Voyager operator continue crash forbidden permission

### ISSUE THREAD

**Issue by futurama92** [appscode/voyager#1483]
Hi!

i continue to see this error on voyage-operator
```
[ffb45024-4d85-4db0-b56c-2841b8d293e0] Deleting Stats Service xxx/voyager-xxx-xxxx-stats
panic: ingresses.extensions "xxx" is forbidden: User "system:serviceaccount:kube-system:voyager-operator" cannot update resource "ingresses/status" in API group "extensions" in the namespace "xxx"
```

Voyage version is the latest: v12.0.0-rc1, i've checked the rbac permission and i have it. 

I've a GKE cluster with private worker node, i use helm on terraform to install and i set the value rbac.create = true.

How could i fix that?

**Comment by aletundo** [comment]
Hi @futurama92,

I faced the same problem two days ago.  The Helm template [cluter-role.yaml](https://github.com/appscode/voyager/blob/master/charts/voyager/templates/cluster-role.yaml#L45) misses the resource `ingresses/status`.

I edited the ClusterRole on-the-fly and it worked, but it should be updated in the chart.

I hope this helps!
