### ISSUE TITLE
One LB per Service?

### ISSUE THREAD

**Issue by manast** [appscode/voyager#1484]
Reading through the documentation I found in the FAQ that the operator is designed so that it creates a new LB per every deployed service. I want to express that this seems to be a showstopper feature, for instance, LB are very expensive, the main reason to use HAProxy is to be able to share 1 LB for many services, otherwise you can likewise just deploy one LB per service yourself, no need for the voyager operator at all!.

**Comment by tamalsaha** [comment]
You can see our reasoning here in FAQ #2: https://github.com/appscode/voyager/blob/master/docs/concepts/overview.md#faq
