### ISSUE TITLE
Disable TLS Version 1.1

### ISSUE THREAD

**Issue by henrikengelbrink** [appscode/voyager#1489]
I'm currently using Voyager as Ingress Controller for my kubernetes cluster and I checked my services with https://www.ssllabs.com/ssltest. The ranking seems to be good, the only problem is that my services are still offering TLS Version 1.1. Is there a way to disable TLS Version 1.1 in Voyager ?

**Comment by tamalsaha** [comment]
You can use custom templates to disable TLS 1.1 https://appscode.com/products/voyager/v12.0.0-rc.2/guides/ingress/configuration/custom-templates/

**Comment by rtrive** [comment]
is it possibile to have an example config to disable tls 1.1? Or add it has a configuration on the yaml file?
