### ISSUE TITLE
Allow send-ing proxy header to backend

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#164]
send-proxy:

https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html

Use-case:
If the backend is a MySQL server, it can use that information to identify the actual client source ip.
https://www.haproxy.com/blog/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/

**Comment by drf** [comment]
I'm interested in helping out. Could you give me some guidance so I can put together a PR?
