### ISSUE TITLE
Various clean ups

### ISSUE THREAD

**Issue by TamalSaha** [appscode/voyager#18]
- [ ] Use `ingress.appscode.com/daemon.nodeSelector` and remove `ingress.appscode.com/daemon.hostname`
- [ ] Don't pass stats password as label. Rather pass a secret name as label. The keys can be

```yaml
username: xyz
password: abc
```

**Comment by sadlil** [comment]
Q1. `ingress.appscode.com/stats.secretName` ->  Is cross namespace support needed for this secret?

**Comment by TamalSaha** [comment]
Let's support any namespace.
If name == a, secretname =a , ns = default
if name == a.b, secretname = a, ns = b

**Comment by TamalSaha** [comment]
Let's make sure ingress and secret will be in the same ns.
