### ISSUE TITLE
UI improvement: allow and parse multi-line custom annotations

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#187]
[Currently, custom annotations are allowed with `ingress.appscode.com/annotations-service`](https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/annotations.md).

It would be a great UI improvement if instead of this:

```
    ingress.appscode.com/annotations-service: '{ "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http", "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*", "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."}'
```

we could use multiline annotations like this:
```
    ingress.appscode.com/annotations-service: |
        {
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
            "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*",
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."
        }
```

Actually I don't even know if this syntax is supported, or if annotations have a length limit. Maybe this should be done in a ConfigMap instead?

**Comment by TamalSaha** [comment]
I don't think there is any length limit on annotation values. If you look at the official Kube object, you will find them some of them have very big annotation values. But there is an overall limit of 1MB per Kubernetes object (not just annotation) from etcd side.

The multiline annotation should be supported already. The requirements is that the value of the annotation has to be a `string -> string` map. The multi-line syntax only exists at YAML level.

**Comment by julianvmodesto** [comment]
Ooh perfect, okay I'm definitely doing multiline wrong then

**Comment by julianvmodesto** [comment]
This works!
