### ISSUE TITLE
Support full spectrum of HAProxy rules

### ISSUE THREAD

**Issue by TamalSaha** [appscode/voyager#21]
Request:
https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html#rewriting-http-requests

Response:
https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html#rewriting-http-responses

Health checks:
https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html

**Comment by TamalSaha** [comment]
From @skuda

I needed to add another haproxy rule to get phpmyadmin fully working

this is the final setup of one backend

 ```backend http-service-xkw4gf
    reqrep ^(GET|POST|HEAD)\ /1/(.*)     \1\ /\2

    acl hdr_location res.hdr(Location) -m found
    rspirep ^Location:\ (https?://phpmyadmin.local(:[0-9]+)?)?(/.*) Location:\ /1/ if hdr_location

    server server-10.200.65.19 10.200.65.19:80```

This way I got the rewrites needed, this is something that is accomplish in Apache mod_proxy with "ProxyPassReverse"

you can get the details here https://www.haproxy.com/blog/howto-write-apache-proxypass-rules-in-haproxy/ (edited)

without that I was able to see the home but every submit button was broken, because it directed to phpmyadmin.local, not phpmyadmin.local/1

**Comment by TamalSaha** [comment]
- [ ] `haproxyRule` or `rawRule` key.
 - [ ] Array of strings
 - [ ] Prefix auto generated acls with `__` prefix

**Comment by sadlil** [comment]
If we use `haproxyRule` / `backendRules` then there is option that we can remove our current existing
`headerRule` and `rewriteRule`. But removing those won't be backward compatible. So should we mark those deprecated for now and introduce the new `backendRule` along side them? @TamalSaha

**Comment by TamalSaha** [comment]
We will keep the old things as is. When we rewrite everything for the new TPR in 1.7, we will review these things. I think there is a good case to be made to have direct support for common HTTP rewrite rules.

**Comment by TamalSaha** [comment]
@skuda, We have added new BackendRule that can used to add any custom acl rules for a backend. This can be used to add response headers. See docs here: https://github.com/appscode/voyager/blob/master/docs/user-guide/component/ingress/backend-rule.md

**Comment by skuda** [comment]
Tested, working fine, thanks!!
