### ISSUE TITLE
RBAC objects for Voyager operator.

### ISSUE THREAD

**Issue by joshk0** [appscode/voyager#241]
The Prometheus operator is bundled with a [set](https://github.com/coreos/prometheus-operator/tree/master/example/rbac/prometheus) of ClusterRole, ClusterRoleBinding, and ServiceAccount that details the specific REST objects that Prometheus operator needs access to in order to do its job.

Can the same be built for Voyager's operator? Otherwise, it is difficult to install on a cluster that is enforcing RBAC.

**Comment by joshk0** [comment]
cc: @julianvmodesto

**Comment by tamalsaha** [comment]
Yeah. I think just need to document it.

Ref: https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html
