### ISSUE TITLE
Support HorizontalPodAutoscaling for HAProxy pods

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#242]
Currently, we can manually set the number of haproxy replicas with `ingress.appscode.com/replicas: "5"`, but it would be great if we could support HPA using CPU or memory metrics to start.

**Comment by tamalsaha** [comment]
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by julianvmodesto** [comment]
Seems that setting up a HPA resource on a specific `voyager-<ingressname>` works okay, but i'm curious if `ingress.appscode.com/replicas: "5"` will affect the HPA? It looks like the annotation updates the Deployment (?) and HPA works as expected w/ any other Deployment.

**Comment by tamalsaha** [comment]
Currently, we set the replica size at the time Deployment is created. After that we leave it unchanged. So, HPA should continue to work. I guess the question is should we enforce the replica size? If not, may be we should call it `ingress.appscode.com/initial-replicas`. Any thoughts?

**Comment by julianvmodesto** [comment]
Ahh okay I wouldn't expect  the controller enforced the replica size. It seems like the current behavior is actually perfect and the number of replicas updates as expected when a HorizontalPodAutoscaler is introduced for a Deployment. 

Maybe there should be no change, just an example of setting up HPA?

**Comment by tamalsaha** [comment]
I guess. If you would like to contribute an example, we are happy to add it to the docs.

**Comment by julianvmodesto** [comment]
Hmm in our Ingress, we have `ingress.appscode.com/replicas: "5"`, but we manually scaled our Voyager pods to 30 with `kubectl scale voyager-frontend --replicas=30`. After some undetermined, seemingly random time, our Voyager pods scaled back down to 5. I'm investigating, but I'm wondering if you're aware if this might happen by Voyager Operator under some conditions? Again, I'm continuing to investigate if there was a different cause, but curious if Voyager Operator might do this.

**Comment by julianvmodesto** [comment]
Oh actually, would Voyager Operator update the Deployment with `ingress.appscode.com/replicas` if Voyager Operator is upgraded?

**Comment by tamalsaha** [comment]
Checking.
