### ISSUE TITLE
voyager-operator should ensure that ServiceAccount/Role/RoleBinding exists for created voyager deploys.

### ISSUE THREAD

**Issue by joshk0** [appscode/voyager#252]
Related to #241 

With RBAC enabled and standard permissions assigned 'default' service account (aka: nothing), when you create an Ingress, it creates a Deployment which uses that account and tries to get access to ConfigMaps. It can't, so voyager doesn't work at all.

Probably the installation guide should involve creating a ServiceAccount for voyager, ClusterRoles and ClusterRoleBindings so that voyager-operator is guaranteed to be able to create Deployments that are capable of reading the necessary ConfigMaps.

**Comment by joshk0** [comment]
sorry, pressed submit too early.

Maybe the Operator could ensure that the ServiceAccount exists, similar to the way it ensures that the TPRs exist. It may have to fatal out trying to create or update the ServiceAccount, ClusterRole, and ClusterRoleBinding.

Then, it would create the Deployment with the hardcoded service account name, knowing that it exists.

**Comment by joshk0** [comment]
cc: @julianvmodesto

**Comment by tamalsaha** [comment]
>> Maybe the Operator could ensure that the ServiceAccount exists, similar to the way it ensures that the TPRs exist. It may have to fatal out trying to create or update the ServiceAccount, ClusterRole, and ClusterRoleBinding.

If RBAC is enabled, operator will need more permissions to check if all these endpoints (GET) and even more permissions to create them (PUT/POST). I think that will give operator more permission, then it should have.

**Comment by joshk0** [comment]
Point taken. Then either:

* The Ingress should support an annotation that defines the serviceAccountName value to use which has ConfigMap permissions
* Or, the service account and entitlements should be an installation fixture that must be installed for anything to work.

**Comment by tamalsaha** [comment]
> Or, the service account and entitlements should be an installation fixture that must be installed for anything to work.

I think that sounds like the way to go.  We are going to have 2 sets of installation options:
- Use default ServiceAccount (as it is today).
- Use  a `voyager-operator` service account with reduced permissions.

Voyager will use the same `serviceAccountName` installed in the operator pod with HAProxy pods, stats side-car, configmaps, etc.

**Comment by joshk0** [comment]
> Voyager will use the same serviceAccountName (default or voyager-operator) installed in the operator pod with HAProxy pods, stats side-car, configmaps, etc.

operator needs many more privileges than the actual voyager, so if possible, it would be nice to specify voyager-operator and voyager service accounts.

latter only needs RO access to ConfigMaps.

**Comment by tamalsaha** [comment]
Fair point! In fact, we have to create a new ServiceAccount in the namespace where Ingress exists. So, operator S/A will need permission to create S/A-s on the fly. Just wish this was simpler.

**Comment by joshk0** [comment]
I feel like you can make each SA an installation fixture. Here's what I'm using right now.

[Cluster Roles](https://gist.github.com/joshk0/5fe682c8856ac86bfdba84d9d539074e)

**Comment by joshk0** [comment]
[Cluster Role Bindings to Created Service Accounts](https://gist.github.com/joshk0/9bcaefed59c1647154366ab7262e66e7)

**Comment by tamalsaha** [comment]
Thanks @joshk0 . This is very helpful. I am going to look into this,

**Comment by tamalsaha** [comment]
@sadlil , Example pr from KubeDB: https://github.com/k8sdb/elasticsearch/commit/d03bd1c3a66c536ecec9ea1fa5690250ac1b5c83
