### ISSUE TITLE
Adding cert manager to existing ingress does not open port 443

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#267]
From https://github.com/appscode/voyager/pull/221#issuecomment-311699723

Updating an existing Ingress with ingress.appscode.com/annotations-service: '{"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "..."}' doesn't seem to add port tcp-443.

**Comment by tamalsaha** [comment]
@sadlil , this should be fixed by https://github.com/appscode/voyager/pull/282/commits/a3654802cbe3029a14bfc3559ef28cc694dd0efb#diff-67df3d6632464ef31af2dd245970341dR56

**Comment by tamalsaha** [comment]
cc: @julianvmodesto  Fixed in master. This will be part of 3.1.0 release.

**Comment by julianvmodesto** [comment]
Excellent, appreciate it
