### ISSUE TITLE
What is the purpose of the --cloud-provider and the --cluster-name flag?

### ISSUE THREAD

**Issue by jason-riddle** [appscode/voyager#27]
https://github.com/appscode/voyager/blob/master/docs/user-guide/README.md#deploy-controller shows `--cloud-provider` and `--cluster-name` being set, but why is this needed? If this tool is running within the cluster, why does it care what provider it's running on and what the cluster name is?

**Comment by TamalSaha** [comment]
@jason-riddle , Voyager can run HAProxy in 2 different modes. These are:

**- DaemonSet**: In this mode, HAProxy is run as DaemonSet using `nodeSelector` and hostNetwork:true. In this mode, HAProxy's IP will be same as the IP address for nodes where it is running. This is supported on any cloud provider (known or unknown to Kubernetes). Voyager will open  firewall if it is a known provider: aws, gce and passed as a flag. If cloud provider is unknown (say running on DigitalOcean), you can leave --cloud-provider flag unset. --cluster-name is not used in this mode. Users are required to configure firewall as needed for cloud providers unknown to Kubernetes,

**- Loadbalancer**: In this mode, a Kubernetes LoadBalancer type service is used to expose HAProxy to the internet. This is supported for cloud providers known to Kubernetes (aws, gce), -cloud-provider and --cluster-name is required to properly setup this loadbalancer. This can give you elastic IP (aws) or reserved IP (gce).

You can choose the mode in your Ingress YAML using labels: https://github.com/appscode/voyager/tree/master/docs/user-guide/component/ingress#configurations-options

By known and unknown cloud provider, I mean providers that have implemented Loadbalancer() and Firewall() interface: https://github.com/appscode/kubernetes/tree/1.5.2-ac/pkg/cloudprovider/providers

Let me know if I answered your question.
