### ISSUE TITLE
configurable HAProxy defaults

### ISSUE THREAD

**Issue by joshk0** [appscode/voyager#280]
We're trying to migrate away from a legacy HAProxy config. Our use case is extremely high volume of HTTP traffic, so low timeout values are very important. Here's what we have:

```
  timeout connect 5s
  timeout queue 5s
  timeout client 60s
  timeout server 60s
  timeout http-request 15s
  timeout http-keep-alive 2s
```

Unfortunately, defaults are as follows, and not configurable at the ingress object level (literally they are hardcoded in the template:)

```
    # Maximum time to wait for a connection attempt to a server to succeed.
    timeout connect         50000

    # Maximum inactivity time on the client side.
    # Applies when the client is expected to acknowledge or send data.
    timeout client          50000

    # Inactivity timeout on the client side for half-closed connections.
    # Applies when the client is expected to acknowledge or send data
    # while one direction is already shut down.
    timeout client-fin      50000

    # Maximum inactivity time on the server side.
    timeout server          50000

    # timeout to use with WebSocket and CONNECT
    timeout tunnel          50000
```

It would be nice to be able to configure these defaults in ExtendedIngress mode.

**Comment by joshk0** [comment]
What if this were exported to a configmap, and the configmap to use as the template can be selected by the ingress object?

**Comment by tamalsaha** [comment]
>  What if this were exported to a configmap, and the configmap to use as the template can be selected by the ingress object?

I don't think that is practical since we regenerate the template based on Kube watcher. But we can add more annotations for this type of things.
