### ISSUE TITLE
Errorfiles

### ISSUE THREAD

**Issue by stevenpall** [appscode/voyager#296]
Hi there,

I'm wondering if there's currently a way to specify an `errorfile` to be used in a backend configuration? This is standard syntax in HAProxy config files, but I'm wondering if there's some way to specify this in an ingress resource definition.

More broadly, is there a way at present to specify arbitrary HAProxy configuration parameters?

Thanks!

**Comment by tamalsaha** [comment]
@stevenpall , this is possible, You can write a Backend Rule for that. https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/backend-rule.md

Example: https://abesto.net/serving-error-pages-from-haproxy/

>  is there a way at present to specify arbitrary HAProxy configuration parameters?

I think this needs to be answered on a case by case basis. With the introduction of BackendRule, it should be  possible to write any rule for a backend. If there is something missing, let us know.

**Comment by stevenpall** [comment]
Perfect, thanks!
