### ISSUE TITLE
Difficulties to setup, scarce docs

### ISSUE THREAD

**Issue by fvigotti** [appscode/voyager#303]
Hi
I've found your ingress controller solution quite interesting in your initial explanation in README.md file..
the main issue I'm facing is that to go fast while working ( and having to implement about an hundred between library and applications I HAVE TO go fast ) people need more example, (or a well written docs ) It's just a suggestion, 
if you want to spread the usage of voyager you have to start with a better docs :) 

after an initial problem to understand what the application does exactly in my cluster now I'm stuck at the point 
that, 
- It's not clear on bare metal what should be done with cloud configuration  (omit? leave empty? )
- the main voyager application   mount /etc/kubernetes and there are available parameters to specify the kubeconfig file, ok, it is necessary or it can use serviceaccount ? the whole guide about that is left to 1 line which is 
`      --kubeconfig string                     Path to kubeconfig file with authorization information (the master location is set by the master flag).
`
which seems an important thing, but in the automated installation is empty?? so it's optional? the default is used?
I've anyway configured correctly kubeconfig ( pointing to the correct full filename path ) I'll test if it's really necessary later..

The points where I'm stuck are: 
- how to use "ingress.appscode.com/node-selector" the only things I know is that it should be specified as yml-map in the ingress.. 
the `whole` internet  have only one reference about this line,  your README.md 
  - https://www.google.com/search?q=ingress.appscode.com%2Fnode-selector#q=%22ingress.appscode.com/node-selector%22
  - https://github.com/search?q=%22ingress.appscode.com%2Fnode-selector%22&type=Code&utf8=%E2%9C%93
so how it works ?  should I use something like 
    ingress.appscode.com/node-selector:
      kubernetes.io/hostname: "$MyNodeHostname"
 in my ingress ? <-- which bring me to the next point :)
- ingress : it seems that a lot of ingress-controller configuration & service should be placed in the ingress.. but , as kubernetes works, 1 ingress-controller works with more ingress ( on different namespaces ) , now how should I configure the ingress-controller from the ingress configuration if I want/need more ingress ( in different namespaces ) ?
   - the configuration is taken from the ingress in kube-system? other configurations (of ingress-controller+service from the ingress) are ignored ? only 1 ingress is allowed (which is the one in the same namespace of the ingress-controller ) ?

I hope to find answers with my request and maybe help you now giving a insight in my difficulties using your software ( which I repeat.. seems very good :) ) 

just to let you know .. some things I'm planning to use which are not possible with the nginx-controller that kubernetes provide:
- access directly statefulset different instances
- use the custom configuration of haproxy to filter allowed ip address to services
- redirect jmx (which are TCP) services though a public ip/dns for easy debugging

one more thing:
I've seen that haproxy stats give stats about each services.. which is good but the names are all like : 
 - http-service-cm4ufh
 - http-service-uykjxd
in a page with 30 of  them.. the mess is guarantee.. there isn't the possibility to add a name?, instead of 
 http-service-$HASH , http-service-$NS-$NAME-$HASH ? I suspect this should be done in haproxy generated configuration but I suppose is doable :)

Thank you for your time,
Francesco

**Comment by fvigotti** [comment]
closing because requests has been splitted in multiple smaller issue ( I started  writing this one then more problems popped up and I've added them to this issue , not very good idea :) ) 
thanks,
Francesco

**Comment by tamalsaha** [comment]
@fvigotti, thanks for your feedback. Our next release 3.2.0 will address the documentation issue.
