### ISSUE TITLE
haproxy stats, named services

### ISSUE THREAD

**Issue by fvigotti** [appscode/voyager#310]
I'm splitting up the issue #303 , in this I'm requesting if it's possible to better name service while creating the haproxy.cfg

because : 
haproxy stats give stats about each services.. which is good but the names are all like :
http-service-cm4ufh
http-service-uykjxd

in a page with 30 of them.. the mess is guarantee.. there is the possibility to add a name?, instead of
http-service-$HASH , http-service-$SERVICENAME-$HASH ? I suppose is doable without big effort :)

Thank you for your time,
Francesco

**Comment by tamalsaha** [comment]
@fvigotti , can you please tell us why do you want this? I understand that one reason is more readable haproxy.config. Are there any other reasons?

**Comment by fvigotti** [comment]
the main reason is readable haproxy stats page ( more readable haproxy.cfg is a bonus :) ) 
with hashed services the stats page is very very hard to read.. it's almost not usable.. 

thanks,
Francesco

**Comment by tamalsaha** [comment]
Ok. We are going to look into this.

**Comment by tamalsaha** [comment]
Hi,
We have updated the logic for generating backend names to be `<svc>.<namespace>:<port>-<6-rand-chars>` .
```
