### ISSUE TITLE
Allow option http-keep-alive and TLS backends

### ISSUE THREAD

**Issue by smerschjohann** [appscode/voyager#343]
Hi,

I looked at the [the haproxy template](https://github.com/appscode/voyager/blob/3243acd62e9c8ad7806b5d6d411c67de1df41d59/pkg/ingress/template/template.go) and found some configurations that I would like to change which is currently not possible:

- support for http-keep-alive instead of http-server-close
- support for HTTPs backends like `server srv01 10.20.30.40:443 weight 1 maxconn 100 check ssl verify none`

Is there a particular reason why you chose http-server-close over http-keep-alive?

**Comment by tamalsaha** [comment]
@smerschjohann , we can make both of these configurable.

Is there a particular reason why you chose http-server-close over http-keep-alive? We don't remember why. We can picked something when we started. :)

**Comment by smerschjohann** [comment]
Ah cool 👍 I'll wait for that release then :)

**Comment by greg-jaunt** [comment]
Looks like I need this too.  Connections to my service fail with the default http-server-close mode.

**Comment by sadlil** [comment]
@greg-jaunt @smerschjohann in our `3.1.*` version there is an work around to add `option http-keep-alive` in the beackend rules.
if you set `option http-keep-alive` as `backendRules` this will apply http-keep-alive for that specif options.
