### ISSUE TITLE
setting  a static port for type nodeport 

### ISSUE THREAD

**Issue by izutheo** [appscode/voyager#344]
I am having an issue setting a static port for the  ingress service when using  type nodeport on bare-metal.
Since i still want to have  a multitude of ports  options available to me I really don't want to change the range in the api server param --service-node-port-range.

I also do  not want to  update the service info manually after creation . Is there anyway of achieving this?
I know i might just be missing something in my configuration.

**Comment by tamalsaha** [comment]
Hi,
We are working on a fix that will allow you to specify the NodePort in your Ingress. https://github.com/appscode/voyager/issues/128

Does that handle your use-case?

**Comment by izutheo** [comment]
Hi  tamalsaha,
Thanks for the quick followup. Yes the fix will resolve my issue.

Thanks

**Comment by tamalsaha** [comment]
Great! This is planned to be fixed in next release 3.2.0

**Comment by DefunctExodus** [comment]
Thanks for the update, I am looking for exactly this as well

**Comment by tamalsaha** [comment]
This has been merged into master. This will be part of 3.2.0 release.

**Comment by tamalsaha** [comment]
Dup #128
