### ISSUE TITLE
Document how to configure DNS in Hostport / NodePort mode

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#354]
Voyager should manage the Route 53 settings for having all of the nodes running HAProxy in the DNS A record.

From our Slack: "It would be great if this was added as a mode of operation for Voyager.  I may be the only person on the planet that is on Amazon but can't use an ELB, though.  Well, maybe also these guys:  https://www.loggly.com/blog/why-aws-route-53-over-elastic-load-balancing/ "

**Comment by tamalsaha** [comment]
external-dns project only works with LoadBalancer, NodePort is not supported. https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#which-kubernetes-objects-are-supported

**Comment by tamalsaha** [comment]
We can use https://github.com/appscode/go-dns to deal with any generic DNS server.

**Comment by greg-jaunt** [comment]
Kops dns-controller may also handle this:

**Comment by tamalsaha** [comment]
``
Setting metadata.annotations.ingress.appscode.com/annotations-pod: '{"dns.alpha.kubernetes.io/external": "name.domain.com"}' exposes the HAProxy nodes perfectly as long as you have dns-controller running (comes with Kops clusters). 
```

**Comment by tamalsaha** [comment]
Merged into https://github.com/appscode/voyager/issues/355
