### ISSUE TITLE
Document external-dns configuration

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#355]
For all 3 modes.
https://github.com/kubernetes-incubator/external-dns

**Comment by tamalsaha** [comment]
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress-voyager
  namespace: vdimov-dev
  annotations:
     ingress.appscode.com/annotations-service: |
         {
           "external-dns.alpha.kubernetes.io/hostname" : "voyager.example.com,voyager-1.example.com,voyager-2.example.com"
         }
     ingress.appscode.com/replicas: '2'
spec:
  rules:
  - host: voyager.example.com
    http:
      paths:
       - backend:
          serviceName: web
          servicePort: '80'

**Comment by sheerun** [comment]
Can't extenral-dns recognize ingress resources?

**Comment by tamalsaha** [comment]
If you use Voyager defined CRDs, external-dns can't automatically detect Intgress. You have to use the `ingress.appscode.com/annotations-service` annotation so that external-dns can pick the necessary info from the Service used to expose HAProxy pods.

**Comment by sheerun** [comment]
Can't Voyager automatically set these annotations to its service? It has access to ingress hosts so in the example above it can generate at least `external-dns.alpha.kubernetes.io/hostname: "voyager.example.com"`

**Comment by tamalsaha** [comment]
The issue is voyager does not know if user is using external-dns, whether external-dns supports user's DNS provider etc. So, we left it a manual setup on Ingress YAML.

**Comment by sheerun** [comment]
Unfortunately it is a chore to write above for every ingress. It would be far more convenient if I could set `dnsProviderIntegration: true` in values.yaml and voyager generated these for me :)

**Comment by sheerun** [comment]
Of course extra documentation is also fine, but external-dns seems to be the tool of choice, it's good to integrate with it.

**Comment by tamalsaha** [comment]
I hear you! We will look into this. This is not a priority for the moment.

**Comment by tamalsaha** [comment]
https://github.com/appscode/voyager/pull/895
