### ISSUE TITLE
Handle SSL frontend and backends

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#396]
https://raymii.org/s/snippets/haproxy_ssl_backends.html
https://www.haproxy.com/doc/aloha/7.0/deployment_guides/tls_layouts.html
https://www.haproxy.com/doc/aloha/7.0/haproxy/tls.html
https://serversforhackers.com/c/using-ssl-certificates-with-haproxy

@sadlil , we need to think through all the cases. `noSSL` field is not enough.

**Comment by sadlil** [comment]
#408
