### ISSUE TITLE
single static port for the ingress resource and not a particular service

### ISSUE THREAD

**Issue by izutheo** [appscode/voyager#404]
I think i might jumped the gone on this, but i was actually asking if there was a way to set a static port for the ingress resource above and not have the port change every time i update the ingress resource.

so following your example above, If i updated the ingress resource with an additional path

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
name: test
namespace: default
annotations:
ingress.appscode.com/type: NodePort
spec:
rules:

host:
http:
paths: /test
backend:
serviceName: test-server
servicePort: 80
nodePort: 32068
paths: /testing
backend:
serviceName: test-server-2
servicePort: 80
So i am basically asking for the ability to have one static port for entry into the cluster and not to a service.

**Comment by tamalsaha** [comment]
Let's continue the conversation in #400, as that has the context.
