### ISSUE TITLE
Basic Auth annotations implementation

### ISSUE THREAD

**Issue by Scukerman** [appscode/voyager#424]
I would love to see basic auth implementation like it Kube Ingress does.
https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#authentication-related

**Comment by tamalsaha** [comment]
- [ ] The annotation could be applied at the Service level . We  may not want this to work on every path.
- [ ] Watch secrets and update the config.
- [ ] With Service level annotation, there might be multiple secrets in the corresponding namespace.
- [ ] Always encrypt secret even if user provided in non encrypted format.

**Comment by tamalsaha** [comment]
#491

**Comment by tamalsaha** [comment]
#555
