### ISSUE TITLE
Handle both TCP and HTTP requests on same frontend

### ISSUE THREAD

**Issue by bverhoeven** [appscode/voyager#430]
As [discussed on Slack](https://appscode.slack.com/archives/C0XQFLGRM/p1504029194000119), I'm currently in a situation where we use HAproxy to handle both TCP and HTTP on the same TCP frontend. 

We're using the TCP content inspection feature (`tcp-request content`) of HAproxy to detect HTTP traffic on the TCP frontend. If HTTP traffic comes in we'll have access to the HTTP request and we're able to use the normal HTTP rule matching (as if the request was being handled by a HTTP frontend).

Example configuration:

```
frontend cloud-fe
  bind *:80
  mode tcp

  tcp-request inspect-delay 5s
  tcp-request content accept if HTTP

  use_backend http_xxx_backend       if { path_beg /xxx }
  use_backend http_yyy_backend       if { path_beg /yyy }

  default_backend tcp_backend
```
We're currently introducing Kubernetes and voyager looks to be the most promising solution for handling Ingress so far. I'd therefore appreciate any help in figuring out if it's possible to achieve something of a similar nature when using voyager.

**Comment by sadlil** [comment]
@bverhoeven i have tried an sample trying to reproduce your scenario, And it is looked like our current implementation do not support this in either way. for tcp you need to set a different rule with port.
i am closing this issue wrt #436, and we will take a brief look on this  matter.
