### ISSUE TITLE
Support tcp/http on the same port

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#436]
> I have 443 port in NodePort type. I have external loadbalancer which can use only 80,443,3306 and 5432 ports (OVH LB). And I point all the TLS this to the one 443 port
In this controller I used an annotation to passthrough TLS traffic -- `ingress.kubernetes.io/ssl-passthrough`

**Comment by sadlil** [comment]
https://github.com/appscode/voyager/issues/430#issue-253758564

**Comment by tamalsaha** [comment]
#491

**Comment by tamalsaha** [comment]
http://timjrobinson.com/haproxy-how-to-run-http-https-on-the-same-port/

**Comment by tamalsaha** [comment]
https://dgl.cx/2010/01/haproxy-ssh-and-ssl-on-same-port
