### ISSUE TITLE
Allow configuring logging

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#439]
Currently, there is no way to configure logging because it is part of the HAProxy config golang template.

The logs are quite noisy for my team to the point of causing node disk usage to fill up.

We would like to set options such as the below.

```
option dontlog-normal
log /dev/log local0 notice alert
option dontlognull
```

As for implementation, it would be great to be able to override logging defaults to add our own configuration.

Ideally, though, it would be even better if we could allow Voyager users to override everything under the `global` section of the HAProxy config (at the user's own risk). I might want to open a separate issue for this since I would like to see this feature.

**Comment by sadlil** [comment]
@julianvmodesto Can you try this out https://github.com/appscode/voyager/pull/403. This should add logging options to your config.

**Comment by tamalsaha** [comment]
The way to do this will be using custom templates. https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/custom-templates.md
