### ISSUE TITLE
Slack channel token_revoked

### ISSUE THREAD

**Issue by Joshuabaker2** [appscode/voyager#48]
I stumbled across voyager today, and thought the features looked really cool! I was hoping to get it set up, but ran into some bugs while following the user guide. Unfortunately, it looks like the slack channel is closed, because when I try to get an invite it says that the token is revoked.

**Comment by TamalSaha** [comment]
Thanks for letting us know Josh. We will fix it soon.

**Comment by TamalSaha** [comment]
I have updated the Slack legacy token. It is working again.
