### ISSUE TITLE
Allow configuring templates per Ingress

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#482]
It's flexible to give us access to the custom templates, but it would be even more flexible to allow changing the templates per Ingress. For example, if we want `global` or `defaults` to be specific for a single Ingress, but use the default templates for all other Ingresses.

**Comment by tamalsaha** [comment]
I think the priority for something like this is very low is my mind. This a polite way of saying WONT_FIX. :)

Having said that I would like to see use-cases for something like this. My general opinion is that if there are common defaults that are can't be set via annotations, we should continue to add them. Custom templates is like an escape hatch for cases that for really unique. So, please file individual cases that can't be handled by current configuration options.

**Comment by julianvmodesto** [comment]
That's fair, will do :)
