### ISSUE TITLE
Support all standard  ingress annotations

### ISSUE THREAD

**Issue by sadlil** [appscode/voyager#491]
- [Ingress Annotations](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md)
- [Advanced Ingress Configuration](https://docs.giantswarm.io/guides/advanced-ingress-configuration/)

| Name | Annotation Support | Alternate |
| --- | :---: | --- |
| **[TLS](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#tls-related)** |
| `ssl-passthrough` | :heavy_check_mark:   |  Use `NoTLS` with specified port | 
| `ssl-redirect` | :heavy_multiplication_x: | `BackendRule` / `FrontendRule` |
| `force-ssl-redirect` | :heavy_multiplication_x: | `BackendRule` / `FrontendRule` | 
| `secure-backends` | :heavy_multiplication_x: | [Backend TLS](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/backend-tls.md) |
| `kubernetes.io/ingress.allow-http` | :heavy_multiplication_x: | |
| `pre-shared-cert` | :heavy_multiplication_x: | |
| `hsts` | :heavy_check_mark: |`FrontendRule` |
| `hsts-max-age` | :heavy_check_mark: | `FrontendRule`|
| `hsts-preload` | :heavy_check_mark: |`FrontendRule` |
| `hsts-include-subdomains` | :heavy_check_mark: | `FrontendRule`|
| **[Authentication](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#authentication-related)** |
| `auth-type` | :heavy_check_mark: | [Basic Auth](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/basic-auth.md) |
| `auth-secret` | :heavy_check_mark: | [Basic Auth](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/basic-auth.md) |
| `auth-realm` | :heavy_check_mark: | [Basic Auth](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/basic-auth.md) |
| `auth-tls-secret` | :heavy_multiplication_x: | |
| `auth-tls-verify-depth` | :heavy_multiplication_x: ||
| `auth-tls-error-page` | :heavy_multiplication_x: ||
| `auth-satisfy` | :heavy_multiplication_x: ||
| `whitelist-source-range` | :heavy_multiplication_x: | [Frontend Rule](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/frontend-rule.md#example-whitelist-ip-addresses-using-frontend-rules) |
|**[URL](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#url-related)**|
| `app-root` | :heavy_multiplication_x: | |
| [`rewrite-target`](https://github.com/kubernetes/ingress-nginx/blob/master/configuration.md#rewrite) | :heavy_multiplication_x: | [Rewrite Rule](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/header-rewrite.md#header-and-url-rewriting) / [Backend Rule](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/backend-rule.md) |
| `add-base-url` | :heavy_multiplication_x: | |
| `base-url-scheme` | :heavy_multiplication_x: | |
| `preserve-host` | :heavy_multiplication_x: | |
| **[Miscellaneous](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#miscellaneous)** |
| `configuration-snippet` | :heavy_multiplication_x: ||
| `enable-cors` | :heavy_check_mark:  | [Frontend Rule](http://blog.nasrulhazim.com/2017/07/haproxy-setting-up-cors/) |
| `limit-connections` | :heavy_multiplication_x: | [Custom template](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/custom-templates.md) with [maxconn](http://www.haproxy.com/blog/use-a-load-balancer-as-a-first-row-of-defense-against-ddos/) |
| `limit-rps` | :heavy_multiplication_x: | [Custom template](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/custom-templates.md) |
| `limit-rpm` | :heavy_multiplication_x: | [Custom template](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/custom-templates.md) |
| `affinity` | :heavy_check_mark: | [Sticky session](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/sticky-session.md) |
| `session-cookie-name` | :heavy_check_mark: | [Custom template](https://github.com/appscode/voyager/blob/release-4.0/docs/user-guide/ingress/custom-templates.md) |
| `session-cookie-hash` | :heavy_check_mark: | |
| `proxy-body-size` | :heavy_check_mark:  ||
| `proxy-pass-params` | :heavy_multiplication_x: ||
| `follow-redirects` | :heavy_multiplication_x: ||
| `kubernetes.io/ingress.global-static-ip-name` | :heavy_multiplication_x: ||
|**[Caching](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md#caching)** ||HAProxy do not support caching directly, if needs to use take a look at [varnish](https://www.haproxy.com/blog/haproxy-varnish-and-the-single-hostname-website/)|
| `cache-enable` | :heavy_multiplication_x: | |
| `cache-generation` | :heavy_multiplication_x: | |
| `cache-ignore-query-params` | :heavy_multiplication_x: | |
| `cache-whitelist-query-params` | :heavy_multiplication_x: | |
| `cache-sort-query-params` | :heavy_multiplication_x: | |
| `cache-ignore-cookies` | :heavy_multiplication_x: | |

**Comment by tamalsaha** [comment]
https://github.com/kubernetes/ingress/blob/defc425cd26de39e2885c8ddd2a0cf8263d0a6b1/controllers/nginx/configuration.md#L352

**Comment by tamalsaha** [comment]
https://www.haproxy.com/blog/haproxy-and-http-strict-transport-security-hsts-header-in-http-redirects/

**Comment by tamalsaha** [comment]
- [ ] approot / rewrite
- [ ] secret change/ regen basic auth
- [ ] ssl-redirect
- [ ] Support tcp/http on the same port

**Comment by tamalsaha** [comment]
crl - https://langui.sh/2010/01/10/parsing-a-crl-with-openssl/

**Comment by tamalsaha** [comment]
Errorfiles: https://discourse.haproxy.org/t/errorfile-not-working/1278/2 CRLF

**Comment by tamalsaha** [comment]
- [ ] approot / rewrite - https://github.com/kubernetes/ingress-nginx/blob/master/configuration.md#rewrite
https://github.com/kubernetes/ingress-nginx/blob/master/examples/rewrite/README.md

We have decided to not support approot annotations. Existing rewrite rules support is more powerful and flexible.

**Comment by tamalsaha** [comment]
rewrite-target annotation is supported since 5.0.0-rc.4

**Comment by stafot** [comment]
Is there a way to have in voyager a functionality similar to `configuration_snippet` of `ingress_nginx`? The goal to achieve is to proxy a custom header across all rules. Is there another way to make it?
