### ISSUE TITLE
Update voyager docs

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#50]
- [x] Make it clear that it should work with any cluster including GKE. 
 - [x] Show how to use along side other ingress controllers (including hidden GKE) https://www.reddit.com/r/kubernetes/comments/62cobg/custom_ingress_controller_on_googe_container/dfwutp8/
 - [x] Document how to install from Chart
 - [x] Certificate does not explain when to use HTTP Ingress
 - [x] Certificate does not explain how to write the provider secret.
 - [x] NodePort
 - [x] Restrict Voyager to once namespace
 - [x] Use with an SSH service

- [x] Route 53
- [x] Multiple Ingress vs one ingress with many services.

**Comment by sadlil** [comment]
https://github.com/appscode/voyager/pull/51

**Comment by tamalsaha** [comment]
`kubectl get ingress.voyager.appscode.com `
