### ISSUE TITLE
[Feature request] Support for tolerations in ingress pod spec

### ISSUE THREAD

**Issue by dseeley-sky** [appscode/voyager#503]
I'm successfully using ingress.appscode.com/node-selector to force the voyager ingress pod to schedule on specific nodes.  It would be nice to also be able to prevent other pods from scheduling to these nodes using taints, and then applying tolerations (as well as node-selectors) to the ingress pod (a new annotation, perhaps ingress.appscode.com/tolerations).  I looked at using a annotation-pod (to set the old scheduler.alpha.kubernetes.io/tolerations annotation), but this does not work post v1.6.

**Comment by tamalsaha** [comment]
This will be supported in next release. This feature is already implemented in master. https://github.com/appscode/voyager/blob/f4d4f2db029b610eb5673f455bd72b2caaf6b5c7/apis/voyager/v1beta1/ingress.go#L95

**Comment by tamalsaha** [comment]
Closing. Please let us know if there are further comments.

**Comment by tamalsaha** [comment]
Yes. This is part of 4.0.0-rc.x . To use this, just how you will use it with Deployments. Please note that it is part of Ingress spec not annotations. Here is an example:

```

**Comment by dseeley-sky** [comment]
Ah - got it, thank you.  Works great!

**Comment by tamalsaha** [comment]
https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/pod-placement.md
