### ISSUE TITLE
Document how to use Host IP as external IP in minikube for LoadBalancer type Service

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#511]
What I do in this case for voyager is use a service type ClusterIP with an ip fixed (like 10.0.0.150) then create a route to it from my machine

## Works with Mac and minikube on virtualbox/vmware providers
```
sudo route -n delete ${K8S_NETWORK} > /dev/null 2>&1 
  sudo route -n add ${K8S_NETWORK} $(minikube ip)
  interface=$(ifconfig 'bridge0' | grep member | awk '{print $2}' | xargs | awk '{print $1}')
  sudo ifconfig bridge0 -hostfilter ${interface}
```

## Linux version
 ```sudo ip route del ${K8S_NETWORK}
  sudo ip route add ${K8S_NETWORK} via $(minikube ip)```

**Comment by tamalsaha** [comment]
Thanks @david92rl for this method.

**Comment by david92rl** [comment]
**K8S_NETWORK** usually is `10.0.0.0/24` but it's worth to double check always. 
On Linux version adding `sudo ip route del ${K8S_NETWORK}` at the beginning will prevent you from errors if the rule is already set.

**Comment by tamalsaha** [comment]
https://github.com/appscode/voyager/pull/895
