### ISSUE TITLE
Allow configuration of error files

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#525]
I'd like to be able to edit the default error files. Perhaps we could make this available for editing in a ConfigMap?

**Comment by tamalsaha** [comment]
https://abesto.net/serving-error-pages-from-haproxy/

**Comment by tamalsaha** [comment]
https://www.haproxy.com/blog/haproxy-and-http-errors-408-in-chrome/

**Comment by tamalsaha** [comment]
ConfigMap key/value
```
503.http : < content of 503.http>
408        : [errrofile /dev/null]
500        : [errorloc https://example.com/503.hlml] 
```

Generated haproxy.cfg
```
errorfile 503 /srv/voyager/errorfiles/503.http
errofile 408 /dev/null
errloc   500 https://example.com/503.hlml
```

**Comment by tamalsaha** [comment]
https://cbonte.github.io/haproxy-dconv/1.7/configuration.html
