### ISSUE TITLE
ocsp stapling

### ISSUE THREAD

**Issue by skuda** [appscode/voyager#531]
Hi,

I am using the amazing feature of voyager that allows generating let's encrypt certificates using ACME DNS-01. The generation is working fine and the site can be visited using SSL with chrome, hsts is working fine too.

Today I tried to visit using Firefox one of the sites we are testing in a new kubernetes using one of those generated SSL certificates and I got this error:
MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

After a check using ssllabs.com I saw this:
```
OCSP Must Staple | Supported, OCSP response not stapled
```

That pointed me to:
https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/

If I change the Firefox about:config section key security.ssl.enable_ocsp_must_staple to false the site works right.

Voyager adds to HAProxy OCSP stapling support? Thanks!

Miguel.

**Comment by tamalsaha** [comment]
I have disabled the OCSP-must-staple for LE issued certificates. This is the simplest solution for now. You will have to reissue certificates to disable this, after the next release of Voyager.

**Comment by tamalsaha** [comment]
Some handy links for future reference:
- https://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/
- http://www.jinnko.org/2015/03/ocsp-stapling-with-haproxy.html
- https://github.com/pierky/haproxy-ocsp-stapling-updater

**Comment by skuda** [comment]
Hi @tamalsaha, 

I am closing the bug because the fix is already merged.
When do you plan to make a new release with the fix?

 Thanks!

**Comment by tamalsaha** [comment]
We hope to get release out no later than early next week.
