### ISSUE TITLE
Update Voyager to use workqueue

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#535]

**Comment by tamalsaha** [comment]
Fixed by #803

**Comment by julianvmodesto** [comment]
This is very interesting, will this be put into a 5.x release too for compatibility w/ 1.8 clusters?

**Comment by tamalsaha** [comment]
We have cut [6.0.0-rc.0](https://github.com/appscode/voyager/releases/tag/6.0.0-rc.0) . Unless any new major issues are found/reported, this will be the next major release.
