### ISSUE TITLE
Name server by pod name instead of endpoint ip

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#550]
Currently, the names given to the HAProxy `server` directive are `pod-{{ip address}}`. HAProxy stats exported to Prometheus are then tagged with `server=pod-{{ip address}}`. Instead of having to use Prometheus' `label_replace` and join the endpoint ip to a pod name, could we give the pod name instead of the endpoint ip to the HAProxy `server` directive?

**Comment by sadlil** [comment]
This is possible, instead of using `epAddress.IP` in [here](https://github.com/appscode/voyager/blob/master/pkg/ingress/parser.go#L122) we need to use
`epAddress.TargetRef.Name  epAddress.TargetRef.Namespace`, If `epAddress.TargetRef != nil`.
