### ISSUE TITLE
NodePort mode adds port to host header rule, but shouldn't

### ISSUE THREAD

**Issue by nhumrich** [appscode/voyager#552]
I am using NodePort mode, so that I can point my own ALB at HAProxy. Using NodePort, I correctly get a service on node port 31485.

In my ingress, I have host based routing, for example `foo.bar.com` goes to my web-gateway. The rule in haproxy configuration shows up as:

`acl host_acl_web-gateway.default:80-bp7jkb hdr(host) -i foo.bar.com:31485`

As you can see, its adding the node port at the end. Which means that routing doesnt actually work correctly. 

Is there anyway to remove the nodeport in the host routing?

**Comment by tamalsaha** [comment]
`ingress.appscode.com/force-service-port: true`
