### ISSUE TITLE
Document GKE cluster RBAC setup

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#564]
- RBAC
- Failed to open Firewall 
```
 $ kubectl describe ingress.voyager.appscode.com -n connexi api
voyager operator        Warning        FirewallUpdateFailed    Failed to ensure firewall, googleapi: Error 403: Required 'compute.instances.list' permission for 'projects/projectname', forbidden
```

**Comment by leonth** [comment]
We fixed this by:
* finding the service account associated with the GCE instance created by GKE
* adding the role "Compute Admin" to that service account

**Comment by tamalsaha** [comment]
@leonth , I found https://github.com/jcbsmpsn/gke-rbac-walkthrough which seems to explain how to get RBAC working with S/A roles in GKE.

**Comment by perplexa** [comment]
It should work after you set either

```
gcloud config set container/use_client_certificate true
```

or

```
export CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=true
```

and then fetch your cluster's credentials again with `gcloud container clusters get-credentials` before applying the RBAC manifests.
