### ISSUE TITLE
HTTP -> HTTPS redirection does not work in 1.8 cluster with AWS cert manager

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#639]
The underlying issue is that in Kubernetes 1.8, Services do not allow duplicate targetPort .
https://github.com/kubernetes/kubernetes/issues/47222

**Comment by tamalsaha** [comment]
There is not much we can do. As a work around, users can avoid HTTP -> HTTPS redirection by setting annotation `ingress.kubernetes.io/ssl-redirect: "false"` .

cc: @julianvmodesto

**Comment by julianvmodesto** [comment]
Yikes!

Less relevant to my use case currently because we're switching to using NodePort Services/Ingresses instead of LoadBalancer Services/Ingresses, but if we want to switch back this is unfortunate :(

**Comment by julianvmodesto** [comment]
That issue is really interesting btw, thanks for the tag. Seems like a lot of projects also use that behavior. Will continue to watch upstream...

**Comment by tamalsaha** [comment]
Why are you switching to NodePort mode? Are you using the new ALB/NLB stuff ?

**Comment by julianvmodesto** [comment]
We encountered this upstream issue with LoadBalancer Services where instances would all be deregistered them re-registered to our ELB on cluster scaling very occasionally: https://github.com/kubernetes/kubernetes/issues/34267

**Comment by tamalsaha** [comment]
That issue is open since Oct, 2016 and not fixed yet. Sigh!

**Comment by tamalsaha** [comment]
This has been reverted https://github.com/kubernetes/kubernetes/pull/53576
