### ISSUE TITLE
Operator doesn't create CRD groups

### ISSUE THREAD

**Issue by cmcarey** [appscode/voyager#643]
I'm following https://github.com/appscode/voyager/blob/master/docs/install.md on a baremetal cluster which uses flanneld for pod networking and has rbac.

After running `./hack/deploy/baremetal.sh --rbac` and running the following commands:

- `kubectl get pods --all-namespaces -l app=voyager --watch` results in:
  - `kube-system   voyager-operator-845568dff4-xbbhm   1/1       Running   1          4m`
- `kubectl get crd -l app=voyager` results in:
  - `No resources found.`

This is the end of the operator logs:
```
W1018 14:21:35.653217       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1018 14:21:35.658911       1 run.go:111] Starting Voyager operator...
I1018 14:21:35.659801       1 operator.go:56] Ensuring CRD registration
F1018 14:23:08.672408       1 run.go:116] timed out waiting for CRD: Get https://10.96.0.1:443/apis/voyager.appscode.com/v1beta1/ingresses: dial tcp 10.96.0.1:443: i/o timeout
```

The operator then restarts and the process repeats ad infinitum.

Has anyone experienced this before and could point me in the right direction?

**Comment by tamalsaha** [comment]
`dial tcp 10.96.0.1:443: i/o timeout` . This is a networking issue. Voyager pod can't connect to kube api server via `kubernetes` Service.

**Comment by cmcarey** [comment]
@tamalsaha It would seem so, I'll raise this with Flannel.
