### ISSUE TITLE
HA Setups using HAProxy 1.8.x

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#647]
From @skuda in Slack:
Every time I upgrade my deployment with a new image version and the pods get replaced slowly I have some downtime because voyager takes a while to detect the new pods IP, there is a set of recommended params to improve this?

During the upgrade process if I try to load the api I get some errors like this one: (edited)

 ```<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

The containers in the pod are using readinessProbe and livenessProbe, and the config for update is that one

 ```spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
```

**Comment by tamalsaha** [comment]
I think it will be a combination of 2 things;

- New pods start started spaced out in time so that the haproxy config can be updated.
- Enable health check on pods at haproxy level. This will allow haproxy to not use unhealthy pods (pod  removed but config  not updated yet). This is possible today only when external name type services are used.

**Comment by skuda** [comment]
Increasing the minReadySeconds to a bigger number, I used 45 seconds in my tests and now the downtime is only the needed for haproxy to restart.

**Comment by tamalsaha** [comment]
https://certsimple.com/blog/haproxy-http2-dynamic-load-balancing-ssl

**Comment by diptadas** [comment]
https://fabianlee.org/2017/10/16/haproxy-zero-downtime-reloads-with-haproxy-1-8-on-ubuntu-16-04-with-systemd/

**Comment by tamalsaha** [comment]
**SO_REUSEADDR** https://idea.popcount.org/2014-04-03-bind-before-connect/

**Comment by davinchia** [comment]
Does this mean upgrading to the latest voyager version will enable 'seamless reloads'?

**Comment by tamalsaha** [comment]
Yes, as described here: https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

**Comment by davinchia** [comment]
Thanks :)

**Comment by davinchia** [comment]
@tamalsaha What kubernetes version do we need for this upgrade to happen?

**Comment by tamalsaha** [comment]
1.9 or above should work.

**Comment by davinchia** [comment]
What version of Voyager is this - 7.4 or master?

**Comment by tamalsaha** [comment]
7.4
