### ISSUE TITLE
Missing Ingress Annotation in Documentation

### ISSUE THREAD

**Issue by labeh** [appscode/voyager#668]
Hello everybody,
there is a missing annotation in the docs:
`ingress.appscode.com/load-balancer-ip: XX.XX.XX.XX` can be used to hand over a predefined static ip adress to the outbound service in gke.

I think this should be added to the annotation-page: https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/ingress-annotations.md

best regards
Lasse

**Comment by tamalsaha** [comment]
It is documented in https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/README.md.

But we should merge them into one doc.
