### ISSUE TITLE
OpenStack support

### ISSUE THREAD

**Issue by piwi91** [appscode/voyager#669]
Is OpenStack support on the roadmap?

**Comment by tamalsaha** [comment]
Hey, thanks for asking! There are few different parts here:

- `ingress.appscode.com: HostPort, NodePort, Internal`: I don't think any special support is needed.

- `ingress.appscode.com: LoadBalancer` : Given Kubernetes supports LoadBalancer type service for Openstack, it is trivial to add support for this in Voyager. The issue that we don't have access to Openstack cluster to test it. If you want to help us test it, we can support this.

**Comment by tamalsaha** [comment]
@piwi91 , I have added LoadBalancer support for openstack provider in #671. I have pushed a docker image `appscode/voyager:openstack` for you to test. If you go to branch `openstack`, you can deploy using `
```
./hack/deploy/openstack.sh [--rabc]
```

**Comment by piwi91** [comment]
Thanks @tamalsaha  for your reply and help. I already thought the LoadBalancer was used, but I get an error "LBType not supported" when I used the "default" settings. LoadBalancers do work when I add a service with type "LoadBalancer" so the Kubernetes controller has access to manage them.
I'll try again using the openstack branch and let you know the results this afternoon.

**Comment by piwi91** [comment]
OK, I deployed voyager but encounter an issue:
```
tlsmounter.go:73] ingresses.extensions "weave-ingress" is forbidden: User "system:serviceaccount:kube-system:voyager-weave-ingress" cannot get ingresses.extensions in the namespace "kube-system"
```

**Comment by piwi91** [comment]
I have one other question about how voyager is using load balancers. Because load balancers are using endpoints, the port is in the 3xxxx range. When I use an ingress to expose port 80, a load balancer is created to use the 3xxxx port range. Is this something that I can prevent with some configuration or is this how kubernetes works using load balancers?

**Comment by tamalsaha** [comment]
I am guessing you are talking about NodePort range. This is configured via kube-apiserver flag:
```
--service-node-port-range portRange                       A port range to reserve for services with NodePort visibility. Example: '30000-32767'. Inclusive at both ends of the range. (default 30000-32767)
```
https://kubernetes.io/docs/admin/kube-apiserver/

**Comment by tamalsaha** [comment]
Are you using in a RBAC enabled cluster? If yes, then you need to install with RBAC mode. `./hack/deploy/openstack.sh --rabc`

**Comment by piwi91** [comment]
I used the RBAC mode. Supervisor is working as expected but the ingress pods won't start. The error line is coming from the ingress pods and not from the supervisor pod.
I know the node port range is configurable. Would you advise to allow all ports? How does voyager work on other deployments when you want to use it as HTTP(S) ingress?

**Comment by tamalsaha** [comment]
Do you see any error in the logs? Can you show the output of 
`kubectl get role voyager-weave-ingress -o yaml`
`kubectl get rolebinding voyager-weave-ingress -o yaml`

> I know the node port range is configurable. Would you advise to allow all ports? How does voyager work on other deployments when you want to use it as HTTP(S) ingress?

If you create a LoadBalancer Service in Openstack, do you get a new IP or do you just get NodePort ? Do you want to run something on port 443? Can you use HostPort mode?

**Comment by piwi91** [comment]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    ingress.appscode.com/origin-api-schema: voyager.appscode.com/v1beta1
    ingress.appscode.com/origin-name: weave-ingress
  creationTimestamp: 2017-10-31T10:46:15Z
  name: voyager-weave-ingress
  namespace: kube-system
  ownerReferences:
  - apiVersion: voyager.appscode.com/v1beta1
    blockOwnerDeletion: true
    kind: Ingress
    name: weave-ingress
    uid: 87b5905d-bd84-11e7-8d9d-020f691c2673
  resourceVersion: "617849"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/voyager-weave-ingress
  uid: b810cdeb-be28-11e7-aa04-02c4f791cd94
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - voyager.appscode.com
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - voyager.appscode.com
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    ingress.appscode.com/origin-api-schema: voyager.appscode.com/v1beta1
    ingress.appscode.com/origin-name: weave-ingress
  creationTimestamp: 2017-10-31T10:46:15Z
  name: voyager-weave-ingress
  namespace: kube-system
  ownerReferences:
  - apiVersion: voyager.appscode.com/v1beta1
    blockOwnerDeletion: true
    kind: Ingress
    name: weave-ingress
    uid: 87b5905d-bd84-11e7-8d9d-020f691c2673
  resourceVersion: "617850"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/voyager-weave-ingress
  uid: b814af35-be28-11e7-aa04-02c4f791cd94
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voyager-weave-ingress
subjects:
- kind: ServiceAccount
  name: voyager-weave-ingress
  namespace: kube-system
```

**Comment by tamalsaha** [comment]
@piwi91, I have pushed an updated operator image with same tag `appscode/voyager:openstack` as before. Please set the `imagePullPolicy: Always` and delete the `voyager-operator-***` pod in kube-system namespace.

Btw, if you have a block of time. we can debug over our slack channel https://slack.appscode.com/ . This is help is get fixed faster.

**Comment by piwi91** [comment]
@tamalsaha I'll take some time to further investigate the issue next week.

**Comment by tamalsaha** [comment]
I have merged the pr as part of 5.0.0-rc.2 release. Please try that branch.

**Comment by piwi91** [comment]
@tamalsaha Can't test it at the moment because there are some issues with the load balancer implementation of OpenStack in K8S (https://github.com/kubernetes/kubernetes/issues/54864). Besides that, I still need to install a QA environment to test these things because I don't want to run them on the pre-production platform. I'll update this ticket once I can test it.

**Comment by tamalsaha** [comment]
@piwi91 , did you get a chance to test this?

**Comment by tamalsaha** [comment]
Please reopen if you are still having issues.
