### ISSUE TITLE
haproxy.cfg:42 rsprep error

### ISSUE THREAD

**Issue by wiktor-starzak** [appscode/voyager#678]
For some reason while creating the config after the line:
`	rsprep ^Set-Cookie:\ (.*) Set-Cookie:\ \1;\ Secure
`i should get new line with:
`mode http`
But for some reason voyager config creation ommits new line and my config gets corrupted. 
I will provide more info if needed.

**Comment by tamalsaha** [comment]
Hi,
can you update the voyager image to `appscode/voyager:tpl` and see if that fixes the issue?

**Comment by wiktor-starzak** [comment]
I think its fixed. The config was created without any problems, i cant test more right now but it seems to be ok. Thank you!
