### ISSUE TITLE
Configure HAProxy to terminate SSL and send PROXYv2

### ISSUE THREAD

**Issue by drf** [appscode/voyager#692]
Looking at the code/documentation, I have seen voyager is capable of configuring HAProxy for accepting incoming connection containing PROXY information. However, I haven't seen, either in the code or the documentation, the possibility of using HAProxy as an SSL Terminator which is in turn capable of relying PROXY(v2) information to another end.

This can be achieved by adding the send-proxy{-v2}{-ssl}{-cn} parameter to bind. Is there an interest for such a feature?

**Comment by tamalsaha** [comment]
I think you are referring to https://github.com/appscode/voyager/issues/164 . If you would like to send a pr, we are happy to review it.

**Comment by drf** [comment]
Yes, my blame for not searching. I'll continue discussion there.
