### ISSUE TITLE
monitor openstack

### ISSUE THREAD

**Issue by lapnt** [appscode/voyager#694]
Hi all,

I want to monitor all services in openstack as : neutro, nova, keystone. but i don't know how to  define services . 
I define :   
define service{
        use generic-service
        host_name AAA
        service_description Keystone
        check_command check_nrpe!check_keystone_api
}
define service{
        use generic-service
        host_name AAA
        service_description Nova Service
        check_command check_nrpe!check_nova-services

}
Dashboard : NRPE: Command 'check_nova-services' not defined 

please help me !!!

**Comment by tamalsaha** [comment]
Hi, I am not sure what you are talking about here. Voyager is a Kubernetes Ingress controller.
