### ISSUE TITLE
One or more Ingress objects are invalid

### ISSUE THREAD

**Issue by OBenned** [appscode/voyager#697]
Hello

Im trying to deploy voyager on baremetal using the baremetal script: ./hack/deploy/baremetal.sh --rbac
But the controller keeps crashing on me, this is the log from the container.

`I1109 10:36:42.089192       1 validator.go:52] Checking ingress ingress-test@default
F1109 10:36:42.089253       1 run.go:139] One or more Ingress objects are invalid: ingress-test@default`

Any idea on what to do from here?

**Comment by tamalsaha** [comment]
Can you share the Ingress YAML for ingress-test?
`kubectl get ingress.voyager.appscode.com ingress-test  -o yaml`

Also, check `kubectl describe ingress.voyager.appscode.com ingress-test`

**Comment by OBenned** [comment]
Hello.

You pointed me in the right direction, there was some old ingress controller form earlier testing, that stil existed i removed that, and now i can start up voyager again.

Thank you!
