### ISSUE TITLE
List of created ingresses?

### ISSUE THREAD

**Issue by sokoow** [appscode/voyager#745]
Hi All,

Is there any way of listing all the ingresses created on voyager yet ? I can create one allright, but  listing ingresses doesn't show a lot.

Also, can you elaborate how the traffic flow works in voyager ? Let's say I hit ingress somehow, what is the flow then ?

Thanks

**Comment by tamalsaha** [comment]
> Is there any way of listing all the ingresses created on voyager yet ?
```
# List all voyager ingress
$ kubectl get ingress.voyager.appscode.com --all-namespaces
```
See here for more: https://github.com/appscode/voyager/blob/master/docs/install.md#using-kubectl

>Also, can you elaborate how the traffic flow works in voyager ? Let's say I hit ingress somehow, what is the flow then ?

First your deploy voyager operator in your cluster.
This operator pod is in charge of running the actual HAProxy pods and updating HAProxy configmaps, issuing ssl certificates from LE, etc

So, when you create an `Ingress` object, voyager operator will start a new deployment of HAProxy pods. These haproxy pods are exposed via a service matching the type of Ingress you are using.
For example, https://raw.githubusercontent.com/appscode/voyager/master/hack/example/e2e.yaml
This shows a NodePort Ingress
Try this example and see that there is a deployment `voyager-test-ingress` and a NodePort service called `voyager-test-ingress`

So, when external clients are calling, the flow is
browser ---(DNS, internet) ---> HAProxy pods ------> backend pods

**Comment by sokoow** [comment]
Cool, thanks for that. Very promising product by the way, well done.

**Comment by tamalsaha** [comment]
Thank you for the kind words @sokoow ! And you are welcome!
