### ISSUE TITLE
AWS ELB Proxy IP forwarded for occurs errors 

### ISSUE THREAD

**Issue by fragtom** [appscode/voyager#749]
We got some trouble regarding the "Keep-source-ip" setting on voyager, if we set this to true, the voyager returns 504 code and error message on controller 

```
Received something which does not look like a PROXY 
protocol header.
```

Our setup is a classic loadbalancer on aws. Found issue regarding ssl on [serverfault](https://serverfault.com/questions/775010/aws-elb-with-ssl-backend-adds-proxy-protocol-inside-ssl-stream), but does not cover our issue.

How to achieve getting IP from source on AWS setup with ingress voyager?

**Comment by igoratencompass** [comment]
Did you enable proxy protocol in the ELB?

**Comment by fragtom** [comment]
No..

**Comment by fragtom** [comment]
Testet with and without enabled proxy protocol.. 

For the moment, we are not able to use the flag `Keep-source-ip`, is there any option to fix that issue, to receive the `X-FORWARDED-FOR` and whitelist that in ingress-voyager?

**Comment by fragtom** [comment]
seems no solution provided here

**Comment by tamalsaha** [comment]
@fragtom, were you able to solve this problem?

**Comment by fragtom** [comment]
no, there is no valid IP from Loadbalancer .. I only get the kubernetes IP.
