### ISSUE TITLE
Source IP affinity

### ISSUE THREAD

**Issue by fragtom** [appscode/voyager#759]
We are not able to build setup for whitelisting our services for dedicated IPs. Reason seems, that we are not able to get `source-ip` from user, we only get the IP from kubernetes node.

What about support of *Source IP affinity* in Voyager?

Status: Setup behind AWS ELB, tested with PROXY-Protocol on/off.

Any help appreciated.

**Comment by tamalsaha** [comment]
https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

**Comment by KresoDenis** [comment]
I think you need 
```
ingress.appscode.com/keep-source-ip: 'true' 
```
which will set 
```
externalTrafficPolicy: Local
```
to voyager ingress service. Then you will be getting your client source IP.

I loose a lot of time learning that WeaveNet does not support this. If you are using weave net as network plugin youll have to swith to Calico, Flannel or something else.

P.S. There is a bash script that need to run periodicly on minions. To make weave net support externalTrafficPolicy: Local

**Comment by tamalsaha** [comment]
@fragtom, does @KresoDenis 's answer help here? If this issue is resolved at your end, please let me know.

**Comment by fragtom** [comment]
no, I think we have a problem on a other side.. thx
