### ISSUE TITLE
Patching voyager ingress fails

### ISSUE THREAD

**Issue by leonth** [appscode/voyager#773]
```
$ cat testpatch.yaml
spec:
 tls:
 - hosts:
   - 'example.com'
   - 'www.example.com'
   secretName: example.com

$ kubectl patch ingress.voyager.appscode.com ingressname --patch "$(cat testpatch.yaml)"
Error from server: unable to find api field in struct Unstructured for the json field "spec"
```

Using voyager 5.0.0-rc8

**Comment by tamalsaha** [comment]
Strategix patch is not supported for CRD types https://github.com/kubernetes/kubernetes/issues/52772

Please use merge patch or json patch https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/
