### ISSUE TITLE
expose port on host 

### ISSUE THREAD

**Issue by hoanhdo** [appscode/voyager#778]
Hi all.

I use voyager ingress. When i listen port on host . after that, i can't expose its again.
> 
> netstat -plan | grep 56790
> tcp6       0      0 :::56790                :::*                    LISTEN      29100/voyager     
> 
> netstat -plan | grep 56791
> tcp6       0      0 :::56791                :::*                    LISTEN      29100/voyager       

What config con expose port on this host.
Thanks.

**Comment by tamalsaha** [comment]
Hi,
I do not understand the problem you are facing. Can you please elaborate further?

**Comment by hoanhdo** [comment]
I have 3 node kubernetes, 1 master and 2 minion node.
I deploy voyager ingress to 2 minion node. I don't remember how i deploy voyager ingress, i run  netstat minon node.

> netstat -plan | grep 56790
>     tcp6 0 0 :::56790 :::* LISTEN 29100/voyager
> 
>     netstat -plan | grep 56791
>     tcp6 0 0 :::56791 :::* LISTEN 29100/voyager

How voyager can listen port on minion nodes.
Thanks.

**Comment by tamalsaha** [comment]
Closed based on our conversation on Slack.
