### ISSUE TITLE
Record events against TPR

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#79]
Use `EventRecorder` to record events.
 - [ ] Errors
 - [ ] Success

**Comment by sadlil** [comment]
@TamalSaha, @saumanbiswas did something similar for appscode/restik? this is a relatively similar task, if he is up for it, can we assign him for the task?

**Comment by TamalSaha** [comment]
I think you need to be familiar with the codebase to write meaningful events. We can move this to 1.5.7
