### ISSUE TITLE
When a pod linked to a service is deleted, Voyager Operator crashes and does not update ConfigMap

### ISSUE THREAD

**Issue by drf** [appscode/voyager#790]
Version: 5.0.0.rc10

Consider the following situation: Service X exposed through a Voyager ingress, with one single replica pod. If the pod gets deleted for any reason (reconfiguration, etc...), Voyager operator crashes consistently with this message:

> I1231 03:05:25.268409       1 services.go:132] [e3277e60-0305-49df-821b-f06c56831fac] Offshoots of voyager.appscode.com/v1beta1 Ingress default/my-ingress exist, trying to update
> I1231 03:05:25.268620       1 parser.go:27] e3277e60-0305-49df-821b-f06c56831fac getting endpoints for  default  port {0 0 }
> I1231 03:05:25.268677       1 parser.go:40] e3277e60-0305-49df-821b-f06c56831fac looking for services in namespace default with name 
> I1231 03:05:25.268784       1 services.go:135] [e3277e60-0305-49df-821b-f06c56831fac] Failed to update offshoots of voyager.appscode.com/v1beta1 Ingress default/my-ingress. Reason: 
> Caused By:
> service "default/" not found
> Stack trace:
> /go/src/github.com/appscode/voyager/pkg/operator/services.go:133                          (*Operator).updateHAProxyConfig
> /go/src/github.com/appscode/voyager/pkg/operator/endpoints.go:56                          (*Operator).initEndpointWatcher.func3
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:202 ResourceEventHandlerFuncs.OnUpdate
> &lt;autogenerated&gt;:1                                                                         (*ResourceEventHandlerFuncs).OnUpdate
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:376 NewIndexerInformer.func1
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 (*DeltaFIFO).Pop
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:150 (*controller).processLoop
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:124 processLoop)-fm
> /go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133  JitterUntil.func1
> /go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134  JitterUntil
> /go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88   Until
> /go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:124 (*controller).Run
> /usr/local/go/src/runtime/asm_amd64.s:2337                                                goexit

And won't update the ConfigMap of the Ingress. For that reason, the Ingress still refers to the dead pod and does not pick up the newly created one.

**Comment by tamalsaha** [comment]
Hi @drf, sorry for late response. Do you still have the original YAML that caused this issue? From the stack trace above, it seems that the backend service name as found as `empty` [service "default/" not found] . This meant, we could not generate the update  haproxy.cfg . So, the old stale config remained inside haproxy pods.

**Comment by tamalsaha** [comment]
Please reopen if you are still having this or have more information to share with us.
