### ISSUE TITLE
Default http->https redirect turns DELETE (and possibly other HTTP verbs) into GET

### ISSUE THREAD

**Issue by drf** [appscode/voyager#816]
Not sure if this is a HAProxy or Voyager bug. When bringing up a standard TLS host rule, http/80 correctly forwards to https. However, if you try to do any operation, such as "DELETE /sth", the redirect will turn into "GET /sth" on https.

**Comment by drf** [comment]
Updated the description - PUT and POST are actually fine, whereas DELETE gets converted into a GET. With the right guidance I could try and provide a patch @tamalsaha

**Comment by tamalsaha** [comment]
@drf,  I have changed the redirect code to 308. According to https://www.haproxy.com/documentation/aloha/7-0/traffic-management/lb-layer7/http-redirection/ , this will preserve original verb.

**Comment by drf** [comment]
Great catch! :)
