### ISSUE TITLE
Upgrade from 5.0.0-rc.11 to 6.0.0-rc.0

### ISSUE THREAD

**Issue by george-oakling** [appscode/voyager#876]
We are using stable chart from kubernetes/charts, and we want to upgrade to 6.0.0-rc.0, but we didnt find how to achieve this, as stable charts are still having the 5.0.0-rc.11 version.

**Comment by tamalsaha** [comment]
Hi, you can use the chart included in this repo. https://github.com/appscode/voyager/tree/master/chart/stable/voyager

I have created a pr to update the stable chart: https://github.com/kubernetes/charts/pull/3738

**Comment by george-oakling** [comment]
Thanks a lot! :)
