### ISSUE TITLE
Preemptible instances issues (6.0.0.rc.0)

### ISSUE THREAD

**Issue by george-oakling** [appscode/voyager#902]
We use preemtible instances in GKE and sometimes the voyager haproxy is not correctly changing the desired pod.

**Comment by tamalsaha** [comment]
When this happens, can you check the following things:

- Is the backend service updated but HAProxy config is not updated?
- Can you check the logs for Voyager operator to see if it received update events for the backend service?
- Does this take around 10 mins to update when there is a delay?

**Comment by george-oakling** [comment]
1. yes, backend is updated, Haproxy not
2. will check
3. no, it is not updated never.

**Comment by tamalsaha** [comment]
What is the version of your Kubernetes cluster ? Can you please show the output of `kubectl version` ?

**Comment by tamalsaha** [comment]
Closing, since no response. Please reopen if  you have more info.
