### ISSUE TITLE
voyager.sh install file now fails for k8s version below 1.9.0

### ISSUE THREAD

**Issue by RisingPhorce** [appscode/voyager#955]
the voyager.sh file uses bash strict mode (set -eou pipefail)
However, the line:

$ONESSL semver --check='>=1.9.0' $KUBE_APISERVER_VERSION

will cause the script to exit because onessl will have a non-zero exit code when the k8s version is below 1.9.0.  Fix:

...
KUBE_APISERVER_VERSION=$(kubectl version -o=json | $ONESSL jsonpath '{.serverVersion.gitVersion}')
set +e
$ONESSL semver --check='>=1.9.0' $KUBE_APISERVER_VERSION
if [ $? -eq 0 ]; then
    export VOYAGER_ENABLE_ADMISSION_WEBHOOK=true
fi
set -e
...

**Comment by tamalsaha** [comment]
Thanks @RisingPhorce ! I have retagged 6.0.0. So, this should be fixed now.
