### ISSUE TITLE
Voyager ingress pod re-created in case of tls setup

### ISSUE THREAD

**Issue by steveum0105** [appscode/voyager#966]
Version Info
k8s : 1.9.6
voyager : either 6.0.0 and 5.0.0-11rc

This issue is related to https://github.com/appscode/voyager/issues/940

I have tested more cases and found details.

The problem is that voyager-ingress pod is re-created(Terminating first, and then Creating).  

This happens when I try to setup TLS hosts only at first time.
(When I only use http, everything is OK)

At first, I set secretNames without hosts in ingress. 
```
tls:
- secretName: test-dev.com
```

Secondly I added hosts keys with values, and **the problem occurs at this time.**
```
tls:
- hosts:
    - steve1234.test-dev.com
  secretName: test-dev.com
```

In addition, I added one more host, and **the problem DOES NOT occurs in this case.**
```
- hosts:
    - steve1234.test-dev.com
    - steve12345.test-dev.com
  secretName: test-dev.com
```

Whenever I add up a **first** 'host domain' with 'hosts' key, then there is the problem.
I cannot even add key 'hosts' without values like this.
```
- hosts: null
  secretName: test-dev.com
```
null is not applied... so I could't test it.

**Comment by tamalsaha** [comment]
@steveum0105, this is actually expected. When you have only HTTP (port 80), HAproxy pods have only port 80 port open. When you provide TLS setup, port 443 on the HAProxy pods are opened. So, we have to restart the pods. If you look at the deployment named `voyager-{ingress-name}`, you should be able to confirm. 

Can you please check and let us know?

**Comment by steveum0105** [comment]
Thank you for your reply!! You are right. It's clear now. 
I expect the way of more soft reboot instead of restarting pods when I select 'HostPort'.
I think it's possible cuz a pod shares network namespace with host in the HostPort mode.
Currently, If I want to use custom ports, ingress pods will be restarted then. I have about 200 pods and it's getting scaled-out, so it takes long...

**Comment by tamalsaha** [comment]
> I expect the way of more soft reboot instead of restarting pods when I select 'HostPort'.

Last I checked, you can't add a new container port to an existing pod. In fact, we just update the deployment spec, Kubernetes takes care of restarting the pods. If you know some ports will be always used, you can leave them open using fake service.

**Comment by steveum0105** [comment]
I understand what you mean. docker does't support, so I can't. I meant I can contribute that in the future..lol. Very appreciate for your reply.
