### ISSUE TITLE
Support for MetalLB

### ISSUE THREAD

**Issue by schubter** [appscode/voyager#970]
i am running MetalLB (https://metallb.universe.tf) on our baremetal clusters with great success and get a LoadBalancer IP assigned even for the voyager service

`
$ kubectl get svc
NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)          AGE
kubernetes                   ClusterIP      10.96.0.1        <none>           443/TCP          211d
voyager-intranet     LoadBalancer   10.105.155.17    xx.xx.xx.31   80:31647/TCP     22h
`

but the haproxy pod keeps crashing with:
`F0405 09:18:34.566804       8 haproxy.go:61] [ingress default/intranet uses unsupported LBType LoadBalancer for cloud provider ]
`

is there a possibility to either include MetalLB as cloudprovider or change the check if a LB-IP has been assigned?

**Comment by tamalsaha** [comment]
If you return `true` from this `switch` https://github.com/appscode/voyager/blob/master/apis/voyager/v1beta1/validator.go#L283 , this should work.

**Comment by schubter** [comment]
thats what i figured, i wasn't sure if there are more things that the cloud provider setting does.
if thats the only thing, do you want me to open a PR?

**Comment by tamalsaha** [comment]
Sure, do you mind trying with your custom build? The build process is described here: https://github.com/appscode/voyager/blob/master/docs/setup/developer-guide/overview.md

**Comment by schubter** [comment]
sure, gladly. i have some other things to attend right now but i should have a pr open after confirming that it works correctly later today.

thanks for the quick response
