### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by mabushey** [appscode/voyager#987]
On a fresh Kubernetes cluster w/1 controller and 3 workers:

```
$ onessl version
Version = 0.2.0
...

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```
```

`$ helm install stable/voyager --name my-release --set cloudProvider=aws --set apiserver.ca="$(onessl get kube-ca)" --set apiserver.enableAdmissionWebhook=true`

These are a bit disconcerting:
```
NOTES:
**This chart is DEPRECATED and moved to https://github.com/appscode/charts**

Set cloudProvider for installing Voyager
```
I tried using this appscode repo for helm but I don't know what has to be passed to helm to override the normal deprecated stable/voyager that  it knows about.

```
$ kubectl get pods --all-namespaces -l app=voyager --watch                                                                                              master 
NAMESPACE   NAME                                  READY     STATUS    RESTARTS   AGE
default     voyager-my-release-6c6d5b58c4-f6n27   0/1       Error     1          20s
default   voyager-my-release-6c6d5b58c4-f6n27   0/1       CrashLoopBackOff   1         24s
default   voyager-my-release-6c6d5b58c4-f6n27   0/1       Running   2         25s
default   voyager-my-release-6c6d5b58c4-f6n27   0/1       Error     2         26s
default   voyager-my-release-6c6d5b58c4-f6n27   0/1       CrashLoopBackOff   2         39s
default   voyager-my-release-6c6d5b58c4-f6n27   0/1       Error     3         56s
```

**Comment by tamalsaha** [comment]
@mabushey , we have moved our charts from stable charts to our own chart repository. Please find the updated instructions here: https://github.com/appscode/voyager/blob/master/docs/setup/install.md#using-helm

Voyager chart is otherwise maintained and can be found here: https://github.com/appscode/voyager/tree/master/chart/voyager

**Comment by tamalsaha** [comment]
Regarding this issue, how tool did you use to provision your cluster?

**Comment by tamalsaha** [comment]
Closing this issue, since there is no update. If you are still having this issue, please reopen and additional information.
