### ISSUE TITLE
CrashLoopBackOff on GKE

### ISSUE THREAD

**Issue by nixon1333** [appscode/voyager#990]
I do not understand the issue here.. 

I am running this the same script on minikue it's running fine. But when i try to run in GKE i'm getting  CrashLoopBackOff. 

<img width="948" alt="screen shot 2018-04-23 at 1 02 56 pm" src="https://user-images.githubusercontent.com/1893934/39111413-cfa11dfe-46f6-11e8-9d65-1f949b574b41.png">

**If i try to describe the pod i'm getting result like this.** 

     Name:           voyager-operator-687d459d5f-gxnwb
     Namespace:      zendesk
     Node:           gke-qa-staging-1-default-pool-02475ed7-c4wq/10.140.0.19
     Start Time:     Mon, 23 Apr 2018 11:33:26 +0600
     Labels:         app=voyager
                     pod-template-hash=2438015819
     Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"zendesk","name":"voyager-operator-687d459d5f","uid":"d6fbd89a-46b7-11e8-a1c5-4201...
                     scheduler.alpha.kubernetes.io/critical-pod=
     Status:         Running
     IP:             10.4.5.122
     Created By:     ReplicaSet/voyager-operator-687d459d5f
     Controlled By:  ReplicaSet/voyager-operator-687d459d5f
     Containers:
       voyager:
         Container ID:  docker://02b0f2891351fe0c2ad6a06ec2e7d20d3f064992647c8447bc0d2db2818b1465
         Image:         appscode/voyager:6.0.0
         Image ID:      docker-pullable://appscode/voyager@sha256:7fc5b28b5eb6d988ca3964cc08b3164e04702ed4d03fbbfffa3decacecb70ca9
         Ports:         8443/TCP, 56790/TCP, 56791/TCP
         Args:
           run
           --v=3
           --rbac=true
           --cloud-provider=gke
           --cloud-config=
           --ingress-class=voyager
           --restrict-to-operator-namespace=true
           --docker-registry=appscode
           --secure-port=8443
           --audit-log-path=-
           --tls-cert-file=/var/serving-cert/tls.crt
           --tls-private-key-file=/var/serving-cert/tls.key
         State:          Waiting
           Reason:       CrashLoopBackOff
         Last State:     Terminated
           Reason:       Error
           Exit Code:    1
           Started:      Mon, 23 Apr 2018 13:01:42 +0600
           Finished:     Mon, 23 Apr 2018 13:01:43 +0600
         Ready:          False
         Restart Count:  22
         Readiness:      http-get https://:8443/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
         Environment:    <none>
         Mounts:
           /etc/kubernetes from cloudconfig (ro)
           /var/run/secrets/kubernetes.io/serviceaccount from voyager-operator-token-z4q4s (ro)
           /var/serving-cert from serving-cert (rw)
     Conditions:
       Type           Status
       Initialized    True
       Ready          False
       PodScheduled   True
     Volumes:
       cloudconfig:
         Type:  HostPath (bare host directory volume)
         Path:  /etc/kubernetes
       serving-cert:
         Type:        Secret (a volume populated by a Secret)
         SecretName:  voyager-apiserver-cert
         Optional:    false
       voyager-operator-token-z4q4s:
         Type:        Secret (a volume populated by a Secret)
         SecretName:  voyager-operator-token-z4q4s
         Optional:    false
     QoS Class:       BestEffort
     Node-Selectors:  <none>
     Tolerations:     CriticalAddonsOnly
                      node.alpha.kubernetes.io/notReady:NoExecute for 300s
                      node.alpha.kubernetes.io/unreachable:NoExecute for 300s
     Events:
       Type     Reason      Age                 From                                                  Message
       ----     ------      ----                ----                                                  -------
       Warning  BackOff     16m (x337 over 1h)  kubelet, gke-qa-staging-1-default-pool-02475ed7-c4wq  Back-off restarting failed container
       Warning  FailedSync  1m (x405 over 1h)   kubelet, gke-qa-staging-1-default-pool-02475ed7-c4wq  Error syncing pod

**If I try to get the log from the pod I'm getting response like this..** 

    I0423 07:06:48.307905       1 logs.go:19] customresourcedefinitions.apiextensions.k8s.io "ingresses.voyager.appscode.com" is forbidden: User "system:serviceaccount:zendesk:voyager-operator" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user "system:serviceaccount:zendesk:voyager-operator"

<img width="1435" alt="screen shot 2018-04-23 at 1 10 48 pm" src="https://user-images.githubusercontent.com/1893934/39111673-cd6d60c8-46f7-11e8-9f17-aa36a71b6947.png">

Any suggestion or help for the issue ?

**Comment by tamalsaha** [comment]
@nixon1333 , how are you installing Voyager? Using script or Helm? It seems that you have not installed rbac rules.

**Comment by nixon1333** [comment]
@tamalsaha  I'm using this command to install
`curl -fsSL https://raw.githubusercontent.com/appscode/voyager/6.0.0/hack/deploy/voyager.sh \
    | bash -s -- --provider=gke --namespace=zendesk --restrict-to-namespace`

**Comment by nixon1333** [comment]
@tamalsaha  
Also can it be the permission issue ? 
`forbidden: User "system:serviceaccount:zendesk:voyager-operator" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user "system:serviceaccount:zendesk:voyager-operator"` 

So if i run 
`kubectl create clusterrolebinding cluster-admin-binding   --clusterrole=cluster-admin   --user=system:serviceaccount:zendesk:voyager-operato`

Will it work?

**Comment by nixon1333** [comment]
@tamalsaha 

> Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tamalsaha** [comment]
```
Unknown user "system:serviceaccount:zendesk:voyager-operator"
```
The service account is not there.

`kubectl get serviceaccount -n zendesk`

**Comment by tamalsaha** [comment]
It seems Voyager was installed without rbac before. You can do two things:

- Uninstsll voyager and then reinstall again and make sure the RBAC objects are creates properly.
or,
- create a the missing service account.  Though, if you are missing ClusterRole, etc, you have to create those too.
```
    kubectl create serviceaccount $VOYAGER_SERVICE_ACCOUNT --namespace $VOYAGER_NAMESPACE
    kubectl label serviceaccount $VOYAGER_SERVICE_ACCOUNT app=voyager --namespace $VOYAGER_NAMESPACE
```

**Comment by tamalsaha** [comment]
Closing this issue, since there is no update. If you are still having this issue, please reopen and additional information.

**Comment by tamalsaha** [comment]
@mcasperson , rbac.create is set to true by default in values file. https://github.com/appscode/voyager/blob/master/chart/voyager/values.yaml#L66

Why do you need to set it manually?

**Comment by mcasperson** [comment]
Because it is not set to true by default in version 5. https://github.com/appscode/voyager/blob/release-5.0/chart/stable/voyager/values.yaml.

And the documentation specifically says to install version 5.

![image](https://user-images.githubusercontent.com/160104/47389412-0376a080-d758-11e8-8a00-64a64a85f733.png)

**Comment by tamalsaha** [comment]
Ah! So, you are using the 5.0.0 version . That clarifies it. Thanks.
