### ISSUE TITLE
Consider implementing LetsEncrypt wildcard certificates

### ISSUE THREAD

**Issue by ThomasKliszowski** [appscode/voyager#994]
As a can see in your [documentation](https://github.com/appscode/voyager/blob/master/docs/guides/certificate/faq.md#how-to-issue-wildcard-certificates-via-lets-encrypt), wildcard certificates are not supported yet.
LetsEncrypt [released ACME v2 with wildcard certificates support](https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579) on March 13rd, do you plan to support this any time soon?

Thank you, love you product BTW :).

**Comment by tamalsaha** [comment]
We want to support this for a while but we are waiting for https://github.com/xenolf/lego/issues/457

**Comment by ThomasKliszowski** [comment]
Oh I see.
Indeed, you asked for updates 21 days ago.
Alright, I guess we have to wait then, thank you Tamal!
